### ISSUE TITLE
avy-isearch example

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/avy#10]
I think that `avy-isearch` should be bound to `isearch-mode-map` for convenience when using `isearch`. For example:

```elisp
(define-key isearch-mode-map (kbd "M-s j") 'avy-isearch)
```

There should be an example on the homepage to make the usage obvious to first time user. I like this package. Good job!

**Comment by abo-abo** [comment]
Thanks. I've changed the binding to a one that I like more.
