### ISSUE TITLE
after-jump hook

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/avy#101]
When editing complicated latex equations, the most convenient way to jump to a symbol like `\alpha` is by jumping to the word `alpha` and then moving back a char. I could jump to the `\`, but that yields dozens of results (and the key is harder to hit).

It would be nice to have some sort of `after-jump-hook`, so that I could have the cursor move back a char automatically after any jump.

    (add-hook 'avy-after-jump-hook (lambda () (when (eq (char-before) ?\\)
                                                (forward-char -1))))

**Comment by abo-abo** [comment]
I'm not sure if a hook is the perfect thing for the situation, since a sequence of function calls would hardly apply in every situation.  Is there any advantage to a hook rather than advising `avy-action-goto`?

**Comment by Malabarba** [comment]
Nope. It was just an idea. I'll use an advice then. 
Thanks for the package!

**Comment by jiri** [comment]
Can we reopen this? `golden-ratio.el` has trouble when the active window is changed using `avy`, to adding a hook to do it manually after an `avy` jump would be valuable. Right now, I'm advising `avy-action-goto`, but I shouldn't have to resort to advising to do this IMO.

**Comment by abo-abo** [comment]
@jiri 

> Right now, I'm advising avy-action-goto, but I shouldn't have to resort to advising to do this IMO.

I'm not a big fan of hooks, especially if they can easily be avoided. What you describe looks like a bug in `golden-ratio`, I suggest fixing it there.  I did touch the code of `golden-ratio-mode` once, it was pretty hairy. These days I avoid every mode that writes to `post-command-hook`.

**Comment by jiri** [comment]
@abo-abo 

While I understand not being a fan of hooks, I think that when you're making a plugin, they *should* be included, if only for the sake of adhering to the patterns of other plugins and emacs itself. I was very confused when I didn't find any hooks in `avy`.

Bottom line, `avy` can potentially change the state of emacs in a way users might want to react to and they should be able to do it "properly". Advising can cause a lot of trouble when mishandled and isn't a replacement for the hook system, which is used thoroughly in Emacs.

I was under the impression of `avy` being the spiritual successor to `ace-jump-mode`, which included hooks and having them would make transitioning easier for people who used them :smile:

**Comment by abo-abo** [comment]
> I was under the impression of avy being the spiritual successor to ace-jump-mode, which included hooks and having them would make transitioning easier for people who used them

The improvement `avy` makes over `ace-jump-mode` is the removal of hooks and callbacks. If those weren't so deeply rooted, there would be no need for `avy` - I'd still be using `ace-jump-mode`.

> Advising can cause a lot of trouble when mishandled and isn't a replacement for the hook system, which is used thoroughly in Emacs.

This simply isn't true any more. Advising is the superior system (thanks to nadvice.el). The hooks that are tied to events (like mode hooks and `post-command-hook`) should remain. But randomly hooking into each package function before and after the call - that's exactly what advice is for.

**Comment by jiri** [comment]
Fair enough.
