### ISSUE TITLE
avy-goto-char got error

### ISSUE THREAD

**Issue by AbyChan** [abo-abo/avy#107]
apply: Wrong number of arguments: #[(ad--addoit-function &optional prompt) "Å	

!
!)" [ad-return-value multiple-cursors-mode ad--addoit-function prompt mc--read-char nil] 2], 3
Quit
or: persp-buffers accessing a non-perspective

Mac OSX

Please  help

**Comment by abo-abo** [comment]
It seems that you're running some advice. You shouldn't do it if you don't understand what it does. Just disable the advice and the package should run fine.

**Comment by AbyChan** [comment]
thank you. but on my linux system without error. same `.emacs.d`

**Comment by abo-abo** [comment]
Try running `emacs -Q -l ~/.emacs.d/init.el`, maybe the advice is loaded from elsewhere.

**Comment by AbyChan** [comment]
Thank you, try it tomorrow on Mac

**Comment by abo-abo** [comment]
Closing to remove the issue clutter. If it's still a problem, reopen or open a new one.
