### ISSUE TITLE
Enhancement idea: Alternative target selections

### ISSUE THREAD

**Issue by tsdh** [abo-abo/avy#11]
I'm a very bad typist.  I can quickly write prose or code because my muscles have memorized the relevant words, but typing nonsense is very hard for me.  And the "words" you have to type to jump to some target with avy-jump are just random sequences of avy-keys.  Every second time I want to jump somewhere, I hit some wrong key and end up somewhere else.

So I've thought it would be very nice if I could select the jump target differently.  Here are some possibilities that I can imagine:

1. One target is pre-selected (ideally the target that's in the middle) and highlighted differently, and then I can select the next/previous target using `C-f`/`C-b`/`<up>`/`<down>`.

2. Instead of using random char sequences from `avy-keys`, use short English (or whatever) words.  The words could come from e.g. a file in `/usr/share/dict/`.  I only have `/usr/share/dict/cracklib-small` but that already contains nearly 1000 words that are one to three letters short.  The problem with this approach is that it will only work nicely with `avy-goto-*-style` `pre` or `post` because then you see the complete word you should type whereas I prefer the `at` style where this is not true.

3. Since I usually manage to type at least the first character correctly, it would help if I could extend the range of `avy-keys` to include also uppercase letters.  But I'd like those to be used only if then a target can be reached with one single key.

Ok, I just wanted to put some ideas to discussion.

**Comment by abo-abo** [comment]
> One target is pre-selected (ideally the target that's in the middle) and highlighted differently, and then I can select the next/previous target using C-f/C-b/<up>/<down>.

Isn't this what `swiper` does? I actually added an option to select a swiper candidate with `avy` on <kbd>C-'</kbd>.  There would usually be less than 10 candidates, and if you make an error, you can call `ivy-resume` and try again.

> Instead of using random char sequences from avy-keys, use short English (or whatever) words.

It's doable, but I don't know if it's worth the hassle. What to do if there's an error when typing the English word? With error handling, this is again `swiper`, only more situational.

> Since I usually manage to type at least the first character correctly, it would help if I could extend the range of avy-keys to include also uppercase letters.

I prefer two lower-case chars to one upper-case. In any case, you can customize `avy-keys`.

> But I'd like those to be used only if then a target can be reached with one single key.

This rule needs to be formalized. Suppose there's <= 26 candidates, then a-z are enough.  If there are <= 72, then a-zA-Z are enough. For more than 72, I could reserve the first or last 26 for A-Z, and proceed with the general algorithm for the rest. So it's doable, I'll think about it.

And, of course, pull requests are welcome on all 3 issues.

**Comment by vermiculus** [comment]
To solve the underlying problem for you, my suggestion would be to force a binary tree by only allowing `fj` (or a quad-tree with `fjir`) as candidates (or whatever characters you can very quickly distinguish). That way, it's just as fast to move about, but you have *zero* movement with *few* fingers.

Having everything on the home row by default is great, but it's only really useful for classically trained typists. :) (Also the health benefits, etc.)

**Comment by tsdh** [comment]
Oleh Krehel <notifications@github.com> writes:

>> One target is pre-selected (ideally the target that's in the middle)
>> and highlighted differently, and then I can select the next/previous
>> target using C-f/C-b/<up>/<down>.
>
> Isn't this what `swiper` does?

Well, except that it's not restricted to the parts of the buffers
visible in a window.  And I can't differentiate multiple matches on the
same line.

> I actually added an option to select a swiper candidate with `avy` on
> <kbd>C-'</kbd>.  There would usually be less than 10 candidates, and
> if you make an error, you can call `ivy-resume` and try again.

I mostly use `avy-goto-char` and when I want to jump to some frequently
occuring letter like e, there can be 100 matches.

>> Instead of using random char sequences from avy-keys, use short
>> English (or whatever) words.
>
> It's doable, but I don't know if it's worth the hassle.

Me, too.  I just wanted to throw in some ideas. :-)

> What to do if there's an error when typing the English word?

That's my point.  I can write real words without errors but have
problems with random "aoe".

>> Since I usually manage to type at least the first character
>> correctly, it would help if I could extend the range of avy-keys to
>> include also uppercase letters.
>
> I prefer two lower-case chars to one upper-case.  In any case, you can
> customize `avy-keys`.

Yes, of course...

>> But I'd like those to be used only if then a target can be reached
>> with one single key.
>
> This rule needs to be formalized.  Suppose there's <= 26 candidates,
> then a-z are enough.  If there are <= 72, then a-zA-Z are enough.  For
> more than 72, I could reserve the first or last 26 for A-Z, and
> proceed with the general algorithm for the rest.  So it's doable, I'll
> think about it.

Yes, something like that was what I've meant.  Basically, I'd use my
home row keys in lower and upper case which would give 22 singe-char
targets.  For the 23th+ matches I'd get multi-char combos, but only with
lower-case letters.  I think, I would an extra variable `avy-extra-keys`
for that.

> And, of course, pull requests are welcome on all 3 issues.

This weekend is packed but I'll see what I can do.

Bye,
Tassilo

**Comment by tsdh** [comment]
Sean Allred <notifications@github.com> writes:

> To solve the underlying problem for you, my suggestion would be to
> force a binary tree by only allowing `fj` (or a quad-tree with `fjir`)
> as candidates (or whatever characters you can very quickly
> distinguish).  That way, it's just as fast to move about, but you have
> *zero* movement with *few* fingers.

Yeah, that also came to my mind.  My avy binding is C-c SPC, so I've
used g, c, and t as avy-keys (g and t are adjacent to c on my German
Dvorak Type II layout).  Typing-wise that's great but in a packed tex
buffer and a frequently occurring char, this usually gives a length of
four or five characters I need to press.

Hm, now I added "ü,." which are the same keys on the other side.  That
seems to be a good compromise between few/easy keys and length of the
key sequence I have to type.

> Having everything on the home row by default is great, but it's only
> really useful for classically trained typists. :)

Indeed.  I've never learned touch-typing.  At some point, I just bought
a keyboard without labels, and by using only that I now can type without
having to look.  But if you asked me for the position of some specific
letter on my keyboard, I'd have no clue.

**Comment by abo-abo** [comment]
> classically trained typists

I'm trained by [The Typing of the Dead](http://en.wikipedia.org/wiki/The_Typing_of_the_Dead). That game was a classic indeed.

**Comment by tsdh** [comment]
:+1:

**Comment by bbatsov** [comment]
I'm trained by `gtypist`. :-)

**Comment by PythonNut** [comment]
@tsdh how would this interact with the issue of #5? Using dictionary words would force you to use `at`, `pre`, or `post`, therefore displacing the text. I doubt there's a closed-form de-bruijn sequence of english words :chart_with_downwards_trend: .

**Comment by tsdh** [comment]
You're right. This idea won't work without displacement of text.

**Comment by bbatsov** [comment]
My two cents are that such a feature doesn't really fit the spirit of the package. Maybe another package should provide something like this, but I think adding it to `avy` would be wrong.

**Comment by tsdh** [comment]
I wouldn't argue with spirit but I also think it wouldn't be to useful. Most of the two or three letter words my duct lists are completely unknown to me so I wouldn't be able to your them with less errors. And the number would quickly shrink to too few if avy-keys is not the full alphabet.

**Comment by tsdh** [comment]
I think I'm just closing this one as the ideas aren't really worth implementing (and I already have a better idea).
