### ISSUE TITLE
org-mode with org-indent-mode and visual-line-mode using de-bruijn doesn't show shortcuts at end of line

### ISSUE THREAD

**Issue by dsedivec** [abo-abo/avy#112]
Thank you for writing avy!  I use it constantly.

I'm having a problem with `de-bruijn` completion as of dddce37cd.  Steps to reproduce:

1. `emacs -Q` (tested on Emacs 24.5.1, NS port, OS X 10.9.5)
2. In `*scratch*` eval:

    ```
    (load "avy.el")
    (setq avy-style 'de-bruijn)
    (org-mode)
    (org-indent-mode)
    (visual-line-mode)
    ```
3. Paste in `* ooooooooooooooooooooooooooooooXXXXXXXXXXo` followed by newline.
4. `M-x avy-goto-char RET o`

Expected behavior: Last `o` in the headline shows a two letter shortcut.

Observed behavior: Last `o` in the headline shows only the first letter of the two letter shortcut, as in this annotated screenshot:
<img width="714" alt="pasted_image_10_25_15__22_45" src="https://cloud.githubusercontent.com/assets/95333/10720915/2055c0b6-7b6a-11e5-9c3b-7a24de34a5a9.png">

This means I can no longer jump to a character at the end of the line, since I can't see the rest of the shortcut.

I think this behavior started between f7ddd4b and dddce37, which I updated to tonight.  This may or may not have something to do with #110, I'm not sure.

**Comment by abo-abo** [comment]
> Observed behavior: Last o in the headline shows only the first letter of the two letter shortcut, as in this annotated screenshot:

This is done intentionally. In some cases, adding a two-letter shortcut to the end of the line would cause the line to be wrapped - moved to a completely different place.  This isn't an issue when `visual-line-mode` is off. I'm adding a fix.

**Comment by dsedivec** [comment]
>> Observed behavior: Last o in the headline shows only the first letter of the two letter shortcut, as in this annotated screenshot:

> This is done intentionally. In some cases, adding a two-letter shortcut to the end of the line would cause the line to be wrapped - moved to a completely different place. This isn't an issue when visual-line-mode is off. I'm adding a fix.

Thank you for the fix!  I can confirm that I am now able to jump to characters at EOL.
