### ISSUE TITLE
org-cycle-agenda-files is bound to C-'

### ISSUE THREAD

**Issue by sshbio** [abo-abo/avy#113]
Not a real issue: a comment maybe.  Just for you to know, because you advised <kbd>C-'</kbd> for `avy-goto-char`.

**Comment by abo-abo** [comment]
Thanks, noted. However, I have to recommend something to make the prominent user suffer less from the choice anxiety. <kbd>C-'</kbd> is a very convenient binding that's not bound in `emacs -Q`.

It's obvious that some packages might recommend it as well, but not much I can do there. It's up to the user to resolve the key binding clash if she decides to use `avy` and has <kbd>C-'</kbd> already bound to something else.

For instance, I have:

```elisp
(global-set-key (kbd "C-M-i") 'iedit-mode)
```

But then I also have to disable the override of <kbd>C-M-i</kbd> by `markdown-mode`:

```elisp
(define-key markdown-mode-map (kbd "C-M-i") nil)
```

**Comment by sshbio** [comment]
We need either too much keys or too much modifiers to bind everything.

Thank you, I take note of it (in my .emacs.d).
