### ISSUE TITLE
Emacs hangs when using avy-goto-char-timer with a pdf-view-mode window

### ISSUE THREAD

**Issue by dsdshcym** [abo-abo/avy#114]
I'm using pdf-tools in emacs to read some pdfs. 
And I also take notes in another window.

When I use `avy-goto-char-timer`, Emacs hangs.

I also noticed that this problem will not happen 
with `avy-goto-char` or any other avy commands.

It seems `avy-ignored-modes` has no effects on
`avy-goto-char-timer`.

**Comment by abo-abo** [comment]
Thanks.
