### ISSUE TITLE
Feature Request: function like avy-subword-1 to also match arbitrary chars

### ISSUE THREAD

**Issue by MrBones118** [abo-abo/avy#116]
Often avy-goto-subword-1 does what I want, and I appreciate being able to look for chars inside a word, subword style, but it's no good for chars that aren't wordlike (e.g. symbols, []{}();'" etc)

Looking for every instance of a char often gives too many matches, and finding the point I want to jump to is too much hassle.

I hacked up  

    (defun avy-subword-or-char (char)
      (interactive "cchar: \n")
      (and (string-equal
          (avy-goto-subword-1 char)
          "zero candidates")
         (avy-goto-char char)))     

Which does the job, but prints extra crap to messages / minibuffer, and and requires a second invocation of avy.
Would something like this be easy to add?

**Comment by abo-abo** [comment]
Could you add an example file text and query, and describe the candidates that you want?

**Comment by MrBones118** [comment]
After a bit of thinking, I'm not so sure I can describe what I want that well.

I like subword searching for alpha numeric characters, but for non-alpha numeric characters, I'd like them to be offered as candidates too, iff they're the first non-alphanumeric character in a sequence of non-alphanumeric characters.

So: a simple one `def f(x: Double) = { x * 2 }`. Here, I'd like to be able to jump to `:`, `{`, `}` as well as anything I could jump to with `avy-goto-subword-1`.

More complex `f :: Double -> Double`.  Here I'd like as candidates anything that worked with `avy-goto-subword-1` plus the first colon in the `::` and the dash but not the angle bracket in `->`.

Does that make sense? Would you like more examples?

**Comment by abo-abo** [comment]
> Does that make sense? Would you like more examples?

What's the `major-mode` you're using? Most of your examples work fine in `fundamental-mode`.

**Comment by MrBones118** [comment]
In fundamental mode, with `def f(x: Double) = { x * 2 }` in buffer, `avy-goto-subword-1` has zero candidates these 'queries':  `SPC`, `=`, `{` `}`. 
I'd like the fallback from subword to be agnostic of major-mode, because some major-modes have odd ideas of what consitutes a word.

**Comment by abo-abo** [comment]
Oops, I was using `avy-goto-word-or-subword-1` with `subword-mode` off:)

See if customizing `avy-subword-extra-word-chars` is enough to solve your problem.
