### ISSUE TITLE
Feature request: avy-move/copy-line/region should optionally insert after current line

### ISSUE THREAD

**Issue by duerrp** [abo-abo/avy#117]
Hi,

I love avy and use it a lot. One thing that keeps bugging me (as an evil-mode user) is that avy-move-line and its siblings inserts before the current line while the vim-inspired pasting inserts after it. Would it be possible to add a variable that controls this, i.e. 
```
(defvar avy-insert-behavior 'above
  "Defines where avy-move-line, avy-copy-line, and avy-copy-region yanks.")
```

**Comment by abo-abo** [comment]
Could you add some examples of use that you're interested in (text and point before command, text and point after command)?

I only ever use `avy-goto-line`, I have no idea which way `ave-move-line` is best implemented.

**Comment by duerrp** [comment]
Sure, e.g., I would like to be able to do the following with avy-copy-line (| denotes the cursor and line 1 is selected:

before:
```
line 1
line 2|
line 3
```
after:
```
line 1
line 2|
line 1
line 3

**Comment by abo-abo** [comment]
Thanks, please test. Use `(setq avy-line-insert-style 'below)`.

**Comment by duerrp** [comment]
@abo-abo Wow, thanks for the fast reaction! Your enhancement works great for `avy-move-line` and `avy-copy-line`. Could you also add it for `avy-copy-region`?

**Comment by duerrp** [comment]
Fantastic, it works perfectly!

Thanks a lot...
