### ISSUE TITLE
Search all windows with universal argument

### ISSUE THREAD

**Issue by paldepind** [abo-abo/avy#118]
I've set

```elisp
(setq avy-all-windows nil)
```

because I prefer that behaviour.

When I invoke an Avy command with a prefix argument all windows in the current frame is searched. Instead I would like to search all windows in _all frames_ when I'm using a prefix argument. It that possible?

Thank you for creating Avy. It has a lot of very impressive features and I enjoy using it.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by paldepind** [comment]
I apologize for the late response. The feature works splendidly! Thank you a lot. avy and ace-window is such a pleasure to use.
