### ISSUE TITLE
avy-copy-region to copy into current buffer

### ISSUE THREAD

**Issue by vadali** [abo-abo/avy#119]
Hey,
Just found out about avy, after using ace for a looong time, it looks really awesome, thanks!

I was a bit puzzled by `avy-copy-region` following behavior:
1. I have two or more buffers opened
2. Point is in a certain position in buffer A
3. I use `avy-copy-region` and select a region in buffer B
4. The lines are copied to buffer B's point, instead of the buffer A.
Is this the desired behavior?

Also, why after selecting the first line, second line selection uses different key combinations? its slightly confusing..

One last comment: when point is in buffer A, and I use `avy-copy-region` on buffer B, after selecting the first line in buffer B, perhaps selection combos in all other buffers should not be seen, as it makes no sense to copy a region "across" two buffers (trying that resulted in some really unpredictable results!)

Thanks!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by vadali** [comment]
Thanks, tested! it now pastes the copied region to the correct buffer. Awesome!

What about the other two points:
1. keeping line selection keys constant between first line and second line selection
2. allowing the region to span a single source buffer only

Should I open different cases for these?

**Comment by abo-abo** [comment]
> Should I open different cases for these?

Yes, with details please.
