### ISSUE TITLE
Odd behavior

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/avy#12]
What's the supposed behavior when looking for something? Should you get all possible single letter triggers before they start becoming multi-letter?

See [this screenshot](https://www.dropbox.com/s/mgx4kjtx58ovssm/Screenshot%202015-05-08%2018.12.37.png?dl=0) to understand what I mean.

**Comment by abo-abo** [comment]
The algorithm works in the following way:

- priority 1: minimize the max tree height.
- priority 2: maximize the amount of leafs at lower height.

In your case, the max tree height is 2. And the amount of leafs on the lower height is 1 (`a`).  If (`s`) were also on height 1, then there would be to space to fit the rest of the candidates => the resulting max tree height would be 3. So the algorithm works correctly here (unless it just cuts off at `fa` like in screenshot).

You can play around with `avy-subdiv` to see how it works:

```elisp
(avy-subdiv 100 6)
;; =>
;; (6 6 6 10 36 36)
```

In this case, there are 100 candidates, and 6 decision keys.  The first three branches contain 6 candidates, which means their leafs are on level 2.  The next three branches have their leafs on level 3, with the fourth branch left with some free space.

**Comment by bbatsov** [comment]
I see. Not sure many people would understand the behaviour, but it makes sense. Maybe you should document it with more examples in the README?

**Comment by abo-abo** [comment]
Added a [wiki page](https://github.com/abo-abo/avy/wiki/Library) for this.
