### ISSUE TITLE
avy-copy-region - selector keys change between first and second line

### ISSUE THREAD

**Issue by vadali** [abo-abo/avy#121]
Steps to reproduce:
1. Open two buffers, A and B, make sure that B has a few lines in it
2. Set mark on buffer A
3. Run avy-copy-region, and select the first line, (say with selector 's') and notice the selector for the last line (say with selector 'd')
4. Notice that after selection, all line selectors change, so the last line is no longer under selector 'd'..

This is an annoyance for me, since when I am determining the region to copy, I automatically look at both selectors (for the first and last line of the region), and would like to enter them fast. This behavior causes me to have an "major-eye-fault" ;) , and I am forced to re-examine the selector for the last line..

**Comment by abo-abo** [comment]
You'll have to choose which one you want solved: #121 or #120. The selector keys depend on the number of candidates.  Fixing #120 will decrease the number of candidates on the second selection, so the selector keys will change.

**Comment by vadali** [comment]
Well, if I have to chose, I chose #121, its much more important to me. 

Regarding #120 I was thinking you could hide and then un-accept the unacceptable candidates from the other buffers.

Thanks!

**Comment by abo-abo** [comment]
Thanks, please check.
