### ISSUE TITLE
no avy-style 'post overlay displayed for candidate at end of buffer

### ISSUE THREAD

**Issue by Antoine-Patel** [abo-abo/avy#125]
If the end of buffer is a character, eg. ")", no overlay is displayed after that character when using `(avy--generic-jump ")" nil 'post)`: it can't be selected. By end of buffer I mean it's not followed by any `\n` or other invisible character: `(progn (end-of-buffer) (and (equal ")" (string (preceding-char))) (eobp)))` should return true.

I began to write and use a few custom avy commands; two of them use `'post` style and should allow to jump to the last character at the end of buffer, so it happens a lot for me recently.

I didn't really look at the part of the source code handling those kind of things (I don't know anything about overlays and such), but maybe this could help (?) : <https://emacs.stackexchange.com/questions/3030/temporary-text-in-window-location-with-no-text-to-propertize-overlay>.

------------------------------
emacs version: `GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian`
avy version: `20151219.630` according to `package-list-packages`

**Comment by abo-abo** [comment]
Thanks.
