### ISSUE TITLE
feature request: auto-toggle case fold 

### ISSUE THREAD

**Issue by Lompik** [abo-abo/avy#126]
Is possible to have have case fold search activated  (only for currently active search) on uppercase letter user input ? If I bother to to enter shoft+letter, most likely I want case fold on.

**Comment by abo-abo** [comment]
See `avy-case-fold-search`.

**Comment by Lompik** [comment]
Ok so the feature seems there but it isnt working as expected I think. in hte case of `avy-goto-work-1` with letter "J", down in `avy--regex-candidates`, the regex is `\\bj`. But then this:

    (not (string= regex (upcase regex)))

will compare "\\BJ" and "\\bj" so it will always be non-nil thus matches ignore case.

But then inside `avy--regex-candidates` even if I use:

    (let ((case-fold-search nil)

still isn't working. The docs says "Automatically becomes buffer-local when set." so wondering if this is related.

**Comment by abo-abo** [comment]
I don't see the problem, `avy-goto-char` with `J` will search only for `J` when `avy-case-fold-search` is nil, and for `J` and `j` when it's t. Works as expected.

**Comment by Lompik** [comment]
I tested with `emacs -Q` and `avy-goto-char` works as expected but the actual problem is with `avy-goto-word` or any avy-* with regex. Basically the condition:

    (not (string= regex (upcase regex)))

should be done on patterns not regexes. In the case of `avy-goto-word`, the regex is `\\bJ` , `\\b` for word boundary and `J` the pattern. `(upcase regex)` return `\\BJ` which is not equal to the original regex `\\bJ`. If it was done on the pattern then `J` (orginal) will match `J` (upcase).

**Comment by abo-abo** [comment]
Should be better now, have a look

**Comment by Lompik** [comment]
works great. See #128
