### ISSUE TITLE
Possible to jump correctly vertically?

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/avy#127]
Lets assume we have the following buffer:

    1. foobar sentence

    2. foobar []sentence

`[]` is the cursor. When I call <kbd>M-x</kbd> `avy-goto-line` and choose the
target (which is sentence 1) and jump into it.

Then the cursor will be placed on column (`(col 1)`) 1:

    1[]. foobar sentence

    2. foobar sentence

Instead of:

    1. foobar []sentence

    2. foobar sentence

I wonder if it would be possible to fix this? With other packages, it placed the cursor correctly.

**Comment by abo-abo** [comment]
`avy-goto-line` behaves like `goto-line`, the built in command. Thus behavior that you describe might be surprising to other users. If you don't want to end up in the first column, use something else like `avy-goto-char`.

**Comment by VanLaser** [comment]
Since I was ready to make a similar request:

I hope it's not a problem if I post this here (it could be a good place) - if (as I think) @ReneFroger is OK with using `avy-goto-line`  integrated with Evil vim-emulation package, the following could be a sufficient workaround:

```elisp
  (evil-define-motion evil-avy-goto-line-keep-column (count)
    "Evil motion for avy-goto-line, restoring column."
    :type exclusive :jump t :repeat abort
    (evil-without-repeat
      (evil-enclose-avy-for-motion
        (evil-save-column (avy-goto-line)))))
  ;; goto-line motion map (example)
  (define-key evil-motion-state-map (kbd "g l") 'evil-avy-goto-line-keep-column))
```

I tried to mimic the method used in `evil-integration.el` to create `avy-goto-` based motions, while taking advantage of the existence of the function `evil-save-column`.

**Comment by abo-abo** [comment]
@VanLaser 

`avy-goto-line` can be easily composed to do what you want:

```elisp
(defun avy-line-saving-column ()
  (interactive)
  (let ((col (current-column)))
    (avy-goto-line)
    (forward-char col)))
```

**Comment by VanLaser** [comment]
Ah, I see - thanks :)

**Comment by VanLaser** [comment]
Thanks! :)

Just a small fix (since `forward-char` happily goes to the next line, if the current one is not long enough):

```elisp
(defun avy-line-saving-column ()
  (interactive)
  (let ((col (current-column)))
    (avy-goto-line)
    (move-to-column col)))
```
