### ISSUE TITLE
at-full, de-bruijn targets broken at EOL when visual-line-mode is enabled

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/avy#129]
**Steps to prepare:**

1. `emacs24.5 -Q`
2. <kbd>M-x</kbd> `package-initialize` <kbd>RET</kbd>
3. <kbd>M-x</kbd> `visual-line-mode` <kbd>RET</kbd>
4. <kbd>M-:</kbd> `(setq avy-keys (list ?a ?b))` <kbd>RET</kbd>
5. <kbd>M-x</kbd> `avy-goto-line` <kbd>RET</kbd>

Note that empty lines do not display the full target. In fact, this applies whenever `avy` tries to jump to the EOL.

**Comment by abo-abo** [comment]
Thanks.
