### ISSUE TITLE
`avy--process` returns "zero candidates"

### ISSUE THREAD

**Issue by whilp** [abo-abo/avy#130]
When `res` is equal to 0, `avy--process` will return the string "zero candidates"; I'd expect `nil` in this case. Noticed in https://github.com/abo-abo/ace-link/pull/23, where I validated the return value with `number-or-marker-p`.

**Comment by whilp** [comment]
Relevant line: https://github.com/abo-abo/avy/blob/808bb80/avy.el#L503-L504

```elisp
    (if (= len 0)
        (message "zero candidates")
```

**Comment by abo-abo** [comment]
I think the function is fine: it calls `(message "zero candidates")` when you pass `nil` as the first argument.  If you don't like this, check the first argument before calling `avy--process`:

```elisp
(let ((cands (whatever)))
  (when cands
    (avy--process cands 'avy--overlay-at-full)))
```

**Comment by whilp** [comment]
Ahhhh, yeah -- makes sense. When I first picked it up, I was surprised that `avy--process` returned something other than one of the candidates or nil. Agreed that checking candidates before is just fine.
