### ISSUE TITLE
Hello, can you add a command?

### ISSUE THREAD

**Issue by jmjoy** [abo-abo/avy#136]
This command is same as avy-goto-word-0 but the word is imagined as just separated by whitespace.

**Comment by abo-abo** [comment]
Please clarify.

**Comment by jmjoy** [comment]
Like this:
``` elisp
(defun avy-goto-unit-0 (arg)
 (interactive "P")
  (avy-with avy-goto-unit-0
    (avy--generic-jump "[^ \n\b]+" arg avy-style)))
```

**Comment by abo-abo** [comment]
You can now customize `avy-goto-word-0-regexp` to do what you want.

**Comment by jmjoy** [comment]
Wonderful!
