### ISSUE TITLE
Quitting avy results in user error

### ISSUE THREAD

**Issue by wasamasa** [abo-abo/avy#137]
Repro:

- `M-x avy-goto-line`
- `C-g`

Expected result: Avy has been aborted, silently (read: without a message in the echo area).

Actual result: Avy has been aborted, loudly ("No such candidate, 7")

Same happens with `ESC` and any sequence not involving alphanumerical characters.  Should be easily fixable by checking whether the character can be a candidate before proceeding any further.

**Comment by abo-abo** [comment]
Thanks, I've silenced the things by default. They're still customizable though:

```elisp
(setq avy-handler-function 'avy-handler-default)
(setq avy-handler-function 'new-handler)

(defun new-handler (_char)
  (message "nothing bad happened")
  (throw 'done 'exit))
```

**Comment by wasamasa** [comment]
Thanks!  FWIW, you can use `?\e` instead of 27.
