### ISSUE TITLE
Overshadowed letters

### ISSUE THREAD

**Issue by KZiemian** [abo-abo/avy#139]
I just start using Avy and it look as very good package. But it doesn''t work like in demo. When I type avy-goto-char-2, with other commands problem is the same, and type "Li" then word "Lisp" turns to "_a_isp" or "_la_sp". Looking at promo, I think that should be "_a_Lisp" and "_la_Lisp", which is much more practical solution. Does anyone have the same problem? I try reinstalling and it doesn't help.

**Comment by abo-abo** [comment]
This is an issue of basic customization. Use <kbd>M-x</kbd> `customize-group avy` and choose the `avy-style` or `avy-styles-alist` that you like.
