### ISSUE TITLE
Quitting avy in ace-link and Ivy

### ISSUE THREAD

**Issue by drot** [abo-abo/avy#140]
Similar to #137, attempt to quit _avy_ selection in _ace-link_ or _ivy-avy_ results in the following errors: 

`funcall-interactively: Wrong type argument: integer-or-marker-p, t` 

for _ace-link_ and:

`ivy-avy: Wrong type argument: integer-or-marker-p, t`

for _ivy-avy_.

**Comment by abo-abo** [comment]
Thanks. It's funny though that what you described are two issues for `ace-link` and `ivy`, none of them relate to `avy`.

I've fixed it in both places. Please test.

**Comment by drot** [comment]
Works fine, thanks.
