### ISSUE TITLE
keybinding not working

### ISSUE THREAD

**Issue by aodock** [abo-abo/avy#141]
Hi, i have installed `avy` on mac. Then added the line `(global-set-key (kbd "C-:") 'avy-goto-char)` to my `~/.emacs` file. When i call avy by keybinding it does not work, instead if i do `M-x avy-goto-char` it works. And this holds for all other remaining avy options too. 

Does `avy` requires any other packages.?

**Comment by abo-abo** [comment]
> Does avy requires any other packages.?

No, you can just load it with `emacs -Q`. Try `emacs -Q -l avy.el` and check that binding a key works. The issue is likely with your config.  Also try something different than <kbd>C-:</kbd>, that binding has issues when used in the terminal.

**Comment by aodock** [comment]
Yes, im using emacs on terminal. It works when i change it from `C-:` to `C-c ;`.. But i like to keep the default... coze, i have just moved from vim to emacs. Any how i will use the one which works. thanks abo-abo

**Comment by abo-abo** [comment]
I'm sorry, but this is a Mac/Terminal/Emacs issue that's not related to avy. I don't know how to solve it, but I avoid the <kbd>C-:</kbd> myself on a Linux machine.

Try to ask here to find a solution: http://emacs.stackexchange.com/questions

**Comment by jdahm** [comment]
@aodock I use Emacs in the terminal at times too, and had so had find a different keybinding. If you have `C-a` cycle between `beginning-of-line` and `back-to-indentation`, you can then use `M-m` for avy, for example. Also, `M-n` is unbound in the global keymap.
