### ISSUE TITLE
proposal: add avy-goto-word-n

### ISSUE THREAD

**Issue by futurist** [abo-abo/avy#143]
Please consider add this function: `avy-goto-word-n`

That to say: you can continuous input char of a word(that's says n), the candidates will update accordingly. until there's less candidate on screen.

Consider 
1. can delete last char if there's an unintentional char; 
2. goto directly or RET-then goto the word, when there's only 1 candidate.

This between the `isearch` style and the currently avy style.

**Comment by abo-abo** [comment]
How is this different from `avy-goto-char-timer`?

**Comment by futurist** [comment]
oh, awesome! just tried it's awesome.

It's not on the README, I missed the func. probably revise the doc?

**Comment by mkleehammer** [comment]
I'd still be interested in a word or symbol version with a timer because it cuts down the number of targets.
