### ISSUE TITLE
Toggle window range with prefix argument broken

### ISSUE THREAD

**Issue by marcowahl** [abo-abo/avy#144]
Hi abo-abo,

Many thanks for avy!  I really like avy.

I think I found a minor bug concerning toggling the windows to be considered.

Precondition:
1. avy-all-windows t
2. Have two windows in a frame each with text containing an 'E'.

Action:
C-u M-x avy-goto-char

Expectation:
The occurances of 'E' are highlighted in the window from where the action was started.

Effect:
The occurances of 'E' in both windows are highlighted.

;; end of ecm report

BTW when starting with avy-all-windows nil the prefix argument has the desired effect.

Thanks for reading, best regards,  Marco

**Comment by abo-abo** [comment]
Have a look at `avy-all-windows-alt`:

> "The alternative `avy-all-windows' for use with \\[universal-argument]."

You need to set it to `nil`. I guess it makes sense to have it `nil` by default as well, since `avy-all-windows` is `t` by default.

**Comment by marcowahl** [comment]
Thanks!

I just didn't see `avy-all-windows-alt.
