### ISSUE TITLE
Doesn't work with non latin letters

### ISSUE THREAD

**Issue by mzavoloka** [abo-abo/avy#146]
For example, I change the input method with C-\ and then want to search for non latin letter. But avy still searches for latin letters. I'm new to emacs, maybe I'm doing something wrong? There's a guy that enabled Russian in his fork of ace-jump-mode, idk if it works, haven't tried it yet:
https://github.com/winterTTr/ace-jump-mode/compare/master...boykov:l10n-russian

**Comment by abo-abo** [comment]
Can't reproduce. Works fine with Cyrillic without any customization. Your Emacs version?

**Comment by mzavoloka** [comment]
25.1.50.2, and I use Spacemacs v.0.105.19, didn't configure anything.

**Comment by dvzubarev** [comment]
It is a problem of evil, see https://bitbucket.org/lyro/evil/issues/605/evil-replace-should-take-into-account
Evil ignores an input method in the normal state.
Avy works as expected, go to the insert state, hit M-m < spc > < any char >

**Comment by mzavoloka** [comment]
@dvzubarev Yes, that was the case, thanks!
