### ISSUE TITLE
Two char, end of line

### ISSUE THREAD

**Issue by quicknir** [abo-abo/avy#153]
Suppose I am using the two char jump command and want to go to the end of the line. What character am I supposed to enter for the new line currently?

**Comment by abo-abo** [comment]
C-j

**Comment by quicknir** [comment]
This is a bit awkward to hit, is it possible to define aliases, or could it be added? E.g. in evil-snipe, it is possible to make it so that a given character will match several other characters. For instance, if it could be made such that spacebar would also match endline. I'm assuming there is a technical reason why enter itself cannot be used?

**Comment by abo-abo** [comment]
You can use the enter now.

**Comment by quicknir** [comment]
Thanks!
