### ISSUE TITLE
Is there a way to leave goto-line chars constantly?

### ISSUE THREAD

**Issue by sandric** [abo-abo/avy#155]
I think it would be killer feature if there was possibility to leave char abbreviation for goto-line constantly, without need to start avy mode by pressing button and see it only then - those abbrv not changing anyway there's 0..constant numbers of lines. I mean if there was a column near line numbers that would always display abbrv for you to type to move to this line.

The thing is as I see most comfortable workflow for me is when I want to move to some line - instead of typing avy shortcut and only then seeing chars I need to type - I will see them from the beginning. And also it would be cool if you could mask entering with some modifier key. With this first idea of constant char cheat sheet - when you realize that you want to move to some line - you look at chars that always there, then pressing C-a + those chars (for example) and voila.

Is it possible to achieve smth similar to that behavior with avy? thx (дяка)!

**Comment by abo-abo** [comment]
Please test `avy-linum-mode`. It's a bit limited for now, but might be enough for your needs.

**Comment by JanPappert** [comment]
I just tried avy-linum-mode but couldn't make it work.
M-x avy-linum-mode yields 'Error in post-command-hook (linum-update-current): (void-function linum--face-width)'.

Curious: avy-linum-mode does not show up in M-x after starting emacs until I switch a buffer.

**Comment by sandric** [comment]
Did you recompiled it? I got it to work and its great. Although I tweaked it a little bit - it turned out that it didn't worked with custom untiping characters as arrows - it can easily be fixed via changing 

`(let* ((path (mapcar #'avy--key-to-char path))
              (str (propertize (apply #'string (reverse path))
                               'face 'avy-lead-face)))`
in avy--linum-strings function. Also I tweaked a little avy--linum-update-window function so that avy not replace line numbers but draw itself near. 

But the big problem for me (maybe its just my old macbook) is that if you open move then one window - its start lagging and work slow.. Don't know if this is fixable somehow thow.

**Comment by abo-abo** [comment]
@JanPappert recompiling should fix it, probably.

@sandric 

> It can easily be fixed via changing let to 

Please open an issue/PR for this. I don't use un-typeable chars, so I can't easily reproduce the issue.

> But the big problem for me (maybe its just my old macbook) is that if you open more then one window - it starts lagging and work slow.. Don't know if this is fixable somehow thow. And anyway, thanks a lot for it, it surprised me how quickly it was made)

How does it behave with regular `linum-mode` and many windows? There's a bit of room for optimization, but it can't be faster than the basic `linum-mode`.

**Comment by JanPappert** [comment]
I already used byte-recompile-directory on my avy-folder to no success.

**Comment by abo-abo** [comment]
@JanPappert `linum--face-width` is defined on line 144 of linum.el. Check if that's the case for you, then it's an Emacs version issue.
