### ISSUE TITLE
Error in avy-goto-subword-1 with empty windows visible

### ISSUE THREAD

**Issue by marcsaegesser** [abo-abo/avy#163]
If I use avy-goto-subword-1 while I have any empty windows visible the command fails with the error: 

> Wrong type argument: char-or-string-p, nil

**Comment by marcsaegesser** [comment]
I cloned avy from github

> cd avy
> emacs -Q --load avy.el
> C-x 2
> C-x C-f  
> fubar.txt
> M-x 
> avy-goto-subword-1 
> c
> Wrong type argument: char-or-string-p, nil
> 

This happens on both my laptop running a source-built emacs-25 (GNU Emacs 25.0.95.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2016-07-04) and on my other computer which is running whatever old version of emacs-24 that comes with Ubuntu these days.

**Comment by abo-abo** [comment]
Thanks for the report, should be fixed now.
