### ISSUE TITLE
avy-goto-word-or-subword-1 does not respect avy-subword-extra-word-chars

### ISSUE THREAD

**Issue by mariusk** [abo-abo/avy#166]
An example: In some of our sources we see people using the javascript style `import {someVar} from ....`. Using `avy-goto-word-1` and pressing `s`, the first letter of `someVar` gets highlighted. But when used with `avy-goto-word-or-subword-1` it does not. Feels like a bug.

**Comment by abo-abo** [comment]
Please give a minimal sample file for this bug.

**Comment by mariusk** [comment]
Create a file `a.js` containing:
```js
import {someVar} from 'someVar';
```
Search for `s` using `avy-goto-word-1` and `avy-goto-word-or-subword-1`. Notice that the former highlights the first `s` in the file while the latter does not.

**Comment by abo-abo** [comment]
Can't reproduce.

**Comment by mariusk** [comment]
Thanks. I just tested, and in text-mode it seems to work as expected, but not in js-mode (which is what I used when I filed the issue). Must be related to what is considered a subword in the different modes. I still do not quite understand why word mode would find it, but not subword, but my knowledge about these things in Emacs is still sketchy.

**Comment by mariusk** [comment]
`avy-goto-subword-1` is to blame it seems. That function does refer to extra chars variable, but it also has a hardcoded regex for "candidates" which may or may not be to blame. Then again, maybe my assumption about how this is supposed to work is completely wrong.

**Comment by mariusk** [comment]
Ah, I now see I have `(subword-mode)` in my `js-mode` hook, which triggers the call to `avy-goto-subword-1`. This may explain why you can't reproduce.

**Comment by mariusk** [comment]
You should be able to reproduce if you test with `avy-goto-subword-1` directly.

**Comment by abo-abo** [comment]
I could reproduce until I realized that I didn't change `avy-subword-extra-word-chars` at all. When I set it to nil, everything works as expected.

The fastest way to test is with `avy-goto-subword-0`.

Here's the code I have now in my config:

```elisp
(defun ora-javascript-hook ()
  (setq-local avy-subword-extra-word-chars nil))
(add-hook 'js-mode-hook 'ora-javascript-hook)
```

**Comment by mariusk** [comment]
I'm not sure `avy-goto-subword-0` works as I would expect. It finds the bracket in front of the `s`, not the `s` itself. Setting extra words to nil however seems to make it work as I would expect however and is a perfectly fine solution. Thanks.
