### ISSUE TITLE
Avy skips lines beginning with a link in org-mode when linum-mode is on

### ISSUE THREAD

**Issue by hardenedapple** [abo-abo/avy#168]
With the org-mode file

```
Hello
[[some link][visible text]] this is a line
Here is some other text
```

and the initialisation file
```elisp
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))
(package-initialize)

(package-refresh-contents)
(unless (package-installed-p 'avy)
  (package-install 'avy))

```

Starting emacs with
`emacs -Q --load testinit.el Test.org`

Then running `avy-goto-word-1` with the character 'i' works fine the first time.
After turning on `linum-mode`, running `avy-goto-word-1` with the character 'i' jumps to the second occurance of the word "is".

I'm using emacs version 24.5.1

The command works if there is a character before the link on that line.
The command works if the line with a link is the first line in the org-mode file.

**Comment by abo-abo** [comment]
Thanks for a very good quality report. Please test.

**Comment by hardenedapple** [comment]
Works for me -- thanks.
