### ISSUE TITLE
Avy is not labelling every character

### ISSUE THREAD

**Issue by fausterjames** [abo-abo/avy#172]
I can't jump to every instance of a character, for instance consider this line : 

`if( c == '\n' ||  c == ' ' || c == '\n') continue;`

Pressing `avy-shortcut SPC` to label all the white spaces will only allow me to jump at the spaces between the `c ==`, all the other spaces after and before the `(, ), |, '` are ignored. Any idea on how to fix this behavior ?

**Comment by abo-abo** [comment]
> avy-shortcut SPC

Which command are you calling? `avy-goto-char` should jump anywhere, maybe you're calling something else?

**Comment by fausterjames** [comment]
I'm using the binding :  `(define-key evil-motion-state-map (kbd "²") #'avy-goto-word-1)`

**Comment by abo-abo** [comment]
Glad to help.
