### ISSUE TITLE
dvorak users?

### ISSUE THREAD

**Issue by joefromct** [abo-abo/avy#173]
Hi, Thanks for Avy.

Is there anyway i can teach Avy to choose keys that are more ideal for a dvorak layout?  I'm assuming somewhere in the code there is priorities on qwerty keys that are accessible. 

Any tips appreciated, thanks,

**Comment by abo-abo** [comment]
See `avy-keys` variable.

**Comment by joefromct** [comment]
Thank you, that works great.
