### ISSUE TITLE
avy is not part of emacs

### ISSUE THREAD

**Issue by dudebout** [abo-abo/avy#174]
The statement on line 11 should be inverted as avy is not part of emacs.

**Comment by abo-abo** [comment]
All packages in GNU ELPA are part of Emacs.

**Comment by dudebout** [comment]
My bad. I did not realize in was in GNU ELPA.

The wording is confusing as you cannot find avy inside the emacs release tarball.

**Comment by abo-abo** [comment]
> you cannot find avy inside the emacs release tarball.

That may change in Emacs 26.
