### ISSUE TITLE
Is this possible with a hydra?

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/avy#175]
I might be pushing things a bit but I would like to have a hydra popup as one of the keys in avy-dispatch-alist.

    (defhydra hydra-avy-action (:color red)
      "Avy actions"
      ("c" avy-action-copy "copy"))

     (add-to-list 'avy-dispatch-alist '(?v . hydra-avy-action/body))

 The idea being avy-got-t-char-2 followed by t characters. Then v should open the hydra to select respective avy actions. Then enter the 2 characters on which the action is performed.

**Comment by abo-abo** [comment]
You can do anything you want if you set `avy-handler-function` to your own function, instead of `avy-handler-default`.
In that function, you have access to the char that the user pressed to call it; the current path is stored in `avy-current-path`.
