### ISSUE TITLE
Matching on arbitrary char sequences

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/avy#178]
In the following use case avy--generic-jump should select multiple arbitrary string-patterns independent of the distinction between sexp and symbols. 
Which avy function would lend itself for this?

```clojure
(avy-with
    avy-goto-?
  (avy--generic-jump
   (regexp-quote "(deftest\\|(defun")
   nil
   avy-style))
```

**Comment by abo-abo** [comment]
Again, drop `regexp-quote` and you're fine.
