### ISSUE TITLE
Inconsistent mark

### ISSUE THREAD

**Issue by muhomor82** [abo-abo/avy#181]
Hi.

I can't find a consistency when using `set-mark` before the `avy-goto-char` command and then perform the jump.

What I'm trying to get is to select a region of interest by activating the mark with `C-SPC` and then jump to the end of the desired region (with `avy-goto-char`), but the mark _most of the times_ deactivated automatically, when the point reaches the destination.

Is there some way to debug/customize this behavior, or maybe even some other command to perform the task alternatively?

**Comment by abo-abo** [comment]
> What I'm trying to get is to select a region of interest by activating the mark with C-SPC and then jump to the end of the desired region (with avy-goto-char), but the mark most of the times deactivated automatically, when the point reaches the destination.

Must be something in your config, it works fine for me. Can you reproduce with `emacs -Q`?

**Comment by muhomor82** [comment]
I used `emacs --no-site-file --no-site-lisp --no-splash` (because -q cancels the **avy** package too) and it behaves exactly the same. But actually I narrowed down the issue: it works perfectly fine if only a single buffer is opened, otherwise something gets wrong. If I close all the buffers again and leave a single one, BOOM, works again.
The fault is on my side, so I need to investigate further. 

Thanks!

**Comment by abo-abo** [comment]
> it works perfectly fine if only a single buffer is opened

Still works fine for me with multiple buffers.

Here's how to test it:

    cd ~/git
    git clone https://github.com/abo-abo/avy
    cd avy
    make run

Alternatively (but then you have to bind `avy-goto-char` yourself):

    cd avy
    emacs -Q -l avy.el

Then <kbd>C-SPC C-c j</kbd> - it works.

**Comment by muhomor82** [comment]
Indeed, it works. I'll try to find which of my other configs causes the issue.

Thanks again.

**Comment by muhomor82** [comment]
By the way, it's a `tabbar-ruler` package which breaks something... When I omit it, everything is fine.

**Comment by abo-abo** [comment]
OK, glad the problem's solved.
