### ISSUE TITLE
avy-action-yank

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/avy#183]
Not sure if others would find this useful or not but I use it:

    (defun avy-action-yank (pt)
      "Copy sexp starting on PT and yank into the current location."
      (avy-action-copy pt)
      (yank))

     (add-to-list 'avy-dispatch-alist '(?y . avy-action-yank))

**Comment by abo-abo** [comment]
Sounds useful, please PR.

**Comment by abo-abo** [comment]
Thanks.
