### ISSUE TITLE
I wish avy-goto-word-1 and avy-goto-char would work in terminal

### ISSUE THREAD

**Issue by k-schmidt** [abo-abo/avy#184]
When I am running emacs in the terminal, `avy-goto-char` and `avy-goto-word-1` won't work but they do when I am in the emacs client application.

**Comment by jdahm** [comment]
They do work. It's the keybinding that doesn't get passed to the process. Try running it e.g. with `M-x avy-goto-char` and you'll find that it does indeed work.
