### ISSUE TITLE
Add avy-goto-word-0-below and avy-goto-word-0-above

### ISSUE THREAD

**Issue by pengux** [abo-abo/avy#185]
It would be nice to limit the scope of the avy-goto-word-0 to above or below the point. As it would save the number of keys required to jump to a certain word.

**Comment by abo-abo** [comment]
Feel free to PR. There are already plenty of `above`/`below` functions to serve as templates.

**Comment by abo-abo** [comment]
Closed by #186

**Comment by pengux** [comment]
Ah, ok will do.
