### ISSUE TITLE
avy-move-region does not move the region to a different buffer

### ISSUE THREAD

**Issue by rangilin** [abo-abo/avy#187]
When I try to move a region in buffer A to buffer B,  avy does not move the selected region in buffer A to B. Instead, it move the region to the cursor position in buffer A. Since `avy-move-line` can work in this scenario, I assume this is a bug in `avy-move-region`.

I can reproduce this issue with `emacs -Q`

### Steps to reproduce:

Step 1:
I want to move two `aaaaaaa` lines from `src` to `desc`, while my cursor is focused in `desc` buffer
![image](https://cloud.githubusercontent.com/assets/849838/24585343/9d73260e-17ba-11e7-9044-e692e8a6adfd.png)
Step2:
Call `avy-move-region`, then press `g`, `h`
![image](https://cloud.githubusercontent.com/assets/849838/24585345/a6911732-17ba-11e7-82b6-4b6a47518bef.png)

### What happen:
The lines got moved to the top of the `src` buffer, where the cursor was at.
![image](https://cloud.githubusercontent.com/assets/849838/24585360/e24cfda4-17ba-11e7-9e24-caac1d12feab.png)

### What I expcet:
The lines should get moved to the `desc` buffer, something like this:
![image](https://cloud.githubusercontent.com/assets/849838/24585414/43e900ac-17bc-11e7-8b52-16e582e5eb94.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by rangilin** [comment]
Looks good, thanks for the quick fix !.
