### ISSUE TITLE
avy-move-region, selecting lines from bottom to top

### ISSUE THREAD

**Issue by duianto** [abo-abo/avy#188]
#### Description
I just learned about the `avy-move-region` command, and while i was testing it, I noticed that it doesn't work the same, if the lines are selected from top to bottom compared to from bottom to top:

#### Steps to reproduce:
1. Write these 5 lines in an empty buffer:
```
1
2
3
--
[cursor]
```
2. `M-x` `avy-move-region` `RET`:
```
a
s
d
f-
```
3. Selected from top to bottom, e.g.: `a` and `d`
```
--
1
2
3
```
This seems to work as expected, the selected lines and the line(s) between them move.
4. In step 2 (undo to get back to step 1 first), if the lines are selected from bottom to top, e.g.: `d` and `a`
```
1
3
--
2
```
Then only the line between the selected lines moves.
5. In step 2, if two lines next to each other are selected from bottom to top, e.g.: `s` `a`, then nothing moves.

#### Doc-string
The `avy-move-region` commands doc-string:
>Select two lines and move the text between them here.

seems to describe the bottom to top behaviour, when at least 3 lines are selected.

If the bottom to top behaviour should be changed to include the selected lines, then the doc-string probably should be updated. Possibly to something like this:
>Select two lines and move the selected lines, including the lines between them, to the cursors location.

#### System Info
Avy
;; Package-Version: 20170402.112
;; Version: 0.4.0
Emacs 25.1.1
Windows 10

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by duianto** [comment]
It works the same way in both directions now, Thank you 👍
