### ISSUE TITLE
avy-resume with last search

### ISSUE THREAD

**Issue by jdahm** [abo-abo/avy#190]
I see there is potentially some support for this already, but it's not clear to me how to use it. It would be useful to on a certain keybinding have the tree overlay reactivate with the last search. Or have a way to start an isearch or swiper with the last avy search. Is there already a way to do this?

**Comment by abo-abo** [comment]
- `avy-resume` is just for `avy` commands.
- You can finish a `swiper` search with <kbd>C-'</kbd> (`swiper-avy`).
- You can resume `swiper` with `ivy-resume`.
- You can't currently start `swiper` from `avy`. That doesn't make too much sense anyway: just start `swiper` anew and input the one char you had in `avy` again.

**Comment by jdahm** [comment]
I already resume ivy-related commands, for instance `swiper`, with `ivy-resume` - it's very helpful, but I still need to train myself to use `swiper-avy`. I'm slowly teaching my muscle memory to use avy for jumping around on screen, and I primarily use `avy-goto-char-timer` for that. I suppose it isn't worth adding a command to forward the couple keystrokes I typed into avy to isearch or swiper.
