### ISSUE TITLE
avy-action-* with avy-goto-line

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/avy#191]
When avy-goto-line is called the actions seem to operate on words.
It would be great if the actions worked on lines when avy-goto-line is called.
The behavior I observe currently is avy-action-copy copies the word instead of the line when avy-goto-line is called.

**Comment by eflanigan00** [comment]
Thank you!  I have never done a PR before but I will take a look.

**Comment by eflanigan00** [comment]
Can you give me some hits about what I might need to change to implement the others?
My elisp isn't very strong and I'm having trouble with understanding how the functions fit together.

**Comment by abo-abo** [comment]
Look at this expression from `avy-action-copy`:

```elisp
(if (eq avy-command 'avy-goto-line)
    (end-of-line)
  (forward-sexp))
```

Replace `forward-sexp` with that for actions you're interested in.

**Comment by eflanigan00** [comment]
Thanks. I have used git to vc my own things but I've never contributed to a github project before. How should I propose the submitted changes?

**Comment by abo-abo** [comment]
You make a pull request on Github. See for example this tutorial: https://yangsu.github.io/pull-request-tutorial/

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by eflanigan00** [comment]
This is great thank you!

For the avy-action-teleport on avy-goto-line can you either put the cursor at the beginning of the line or insert a new line and put the cursor on the new line. I'm not sure which is better behaviour, I think at the beginning of the line that was teleported but I'm not sure.
