### ISSUE TITLE
way to search relative to cursor

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [abo-abo/avy#195]
I'm wondering if there is a way to start a search based on the cursor. Right now regardless of where the cursor is. 

The nice thing about that feature is that:
1) it only takes one character to move to words closest to the cursor
2) it allows you to use avy with macros.

- because after jumping to a certain word or character with a certain char sequence, that same char sequence will be the next candidate. Right now the char sequence is always on the same candidate.

Example of search with vim-easy motion with cursor on line with '(setq avy-keys (number-sequence a? ?z))'
![screenshot 2017-04-30 22 31 52](https://cloud.githubusercontent.com/assets/9679243/25570633/ec5e6ca6-2df4-11e7-9ce9-88d92d754b07.png)

Example of regular avy search when mouse is at same location.
![screenshot 2017-04-30 22 33 27](https://cloud.githubusercontent.com/assets/9679243/25570805/67ebdcd6-2df6-11e7-94a7-6260a0125896.png)

**Comment by abo-abo** [comment]
It's possible to implement. But I don't see it as priority: both approaches have their advantages and disadvantages.

PRs welcome.

**Comment by Luis-Henriquez-Perez** [comment]
Ok. Thank you.
