### ISSUE TITLE
Define a global-set-key instead of using the universal-argument

### ISSUE THREAD

**Issue by mtourne** [abo-abo/avy#196]
I'm starting to use avy quite a bit in my workflows and I like the behavior avy-all-windows to be set to 'all-frames.

But often I'd like to limit to the current window, which works great with C-u followed by my avy shortcut.

I'd like to set a one-key shortcut for that behavior specifically. 

This may not be specific to avy, and more of a :
"how do I write a wrapper function that gets the universal-argument prefixed behavior". 
Unfortunately I wasn't able to find how to do that easily.

Thanks!

**Comment by pheaver** [comment]
Hi, yes, this is a basic emacs question that isn't specific to avy.

You want to define a new function that just wraps around the other, e.g. like this (I'm guessing):

    (defun my-avy-all-windows (interactive) (avy-all-windows t))

**Comment by abo-abo** [comment]
@pheaver Thanks, I agree.

**Comment by mtourne** [comment]
I know it's a basic emacs question.. but maybe useful to someone else.

And I can't crack it with something like this; would you mind helping me?

```(defun avy-goto-char-timer-this-window
  (interactive)
  (avy-all-windows nil)
  'avy-goto-char-timer
  )```

**Comment by abo-abo** [comment]
```elisp
(defun avy-goto-char-timer-this-window ()
  (interactive)
  (let ((avy-all-windows nil))
    (avy-goto-char-timer)))
```
