### ISSUE TITLE
It would be nice to use avy to zapping.

### ISSUE THREAD

**Issue by AttilaVM** [abo-abo/avy#201]
Emacs built-in zap-to-char is powerful function, however sometimes not enough, it would be nice to zap in avy style. I wrote a dirty little function, which does the trick...

```
(defun my/avy-zap-to-char-2 ()
  "Jump to the currently visible CHAR1 followed by CHAR2.
The window scope is determined by `avy-all-windows' (ARG negates it)."
  (interactive)
	(call-interactively 'set-mark-command)
	(call-interactively 'avy-goto-char-2)
	(call-interactively 'kill-region))
```

Since I am not elisp expert, it is very likely that it is not very idiomatic...

**Comment by abo-abo** [comment]
There's already a package on MELPA for this: https://github.com/cute-jumper/avy-zap. See if it works for you.
