### ISSUE TITLE
Entering unicode characters

### ISSUE THREAD

**Issue by aravart** [abo-abo/avy#203]
Is there any way to jump to unicode characters with avy-goto-char? In isearch-forward, for example, C-x 8 allows you to enter unicode. (My source files these days tend to have a lot of unicode)

**Comment by abo-abo** [comment]
It works if you set the input method with e.g. `toggle-input-method`.

For example, I use `(setq default-input-method "ukrainian-computer")`. So I:

- `toggle-input-method` away from English (it's buffer-local), key biding `C-\`.
- possibly type some Ukrainian chars
- call `avy-goto-char` (the key binding isn't affected by the input method)
- press the physical key `a` which translates to `ф` to search for `ф`
- `toggle-input-method` back to English

This only works if your Unicode char is a plain key in some input method. There are input methods for Greek chars, math etc.
