### ISSUE TITLE
[feature request] Case sensitivity

### ISSUE THREAD

**Issue by rieje** [abo-abo/avy#206]
If character is capitalized, show only capitalized matches. If character is lower case, have allow an option to match both upper case and lower case or just lower case. The point of this is to reduce the number of matches so that it is more likely that a selection only requires 1 character. 

It's not so much that more letters mean you have to type more to select the one you want out of the matches--it's so it's more predictable (because it's more likely) that only 1 character is required for selection. This predictability in my experience makes avy feel more natural, which is important for something that requires a context switch in the brain because you need to read and enter "random" characters to get to where you want.

**Comment by abo-abo** [comment]
Use:

    (setq avy-case-fold-search nil)
