### ISSUE TITLE
Request avy-action-kill-yank

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/avy#207]
(defun avy-action-kill-yank (pt)
      "Kill sexp starting on PT and yank into the current location."
      (avy-action-kill-stay pt)
      (yank))

    (add-to-list 'avy-dispatch-alist '(?w . avy-action-kill-yank))

**Comment by abo-abo** [comment]
Thanks.

**Comment by eflanigan00** [comment]
No problem, I like teleport.
