### ISSUE TITLE
After installing avy and restarting Emacs: «autoloading failed to define function»

### ISSUE THREAD

**Issue by shackra** [abo-abo/avy#22]
After installing `avy`, assigning keybindings and restarting Emacs, I get these errors:

```
command-execute: Autoloading failed to define function avy-goto-char
command-execute: Autoloading failed to define function avy-goto-line
command-execute: Autoloading failed to define function avy-goto-word-1
```

After installing `avy` I tried it and everything was fine, but now after restarting it doesn't works!

**Comment by duerrp** [comment]
I think the reason may be a conflict with an old version of ace-window. In my case updating all packages fixed this issue.

**Comment by shackra** [comment]
Yup. Updating `ace-window` fix this problem!

**Comment by abo-abo** [comment]
Glad the problem fixed itself:)
