### ISSUE TITLE
Use enter for end of line in avy-goto-char-timer

### ISSUE THREAD

**Issue by quicknir** [abo-abo/avy#220]
Hello, this issue is very similar to #153 . I'd like to be able for avy-goto-char-timer to recognize the enter key as the end of line for jumps. I think that enter currently ends the timer early, which I understand some people may rely on. Maybe an option could be used, so that if set/unset, enter is recognized as a normal character, otherwise it ends the timer early?

**Comment by abo-abo** [comment]
You can use <kbd>C-j</kbd> to enter a newline.

**Comment by quicknir** [comment]
Yes, I'm familiar (you told me that when I opened the other issue :-) ), just hitting C-j is a bit awkward, especially since I don't have much time to do it in, compared to typing what I see. If you don't love the idea of merging this in, I'm more than happy to have a small hack in my .emacs (if you can tell me what the hack would look like).

**Comment by quicknir** [comment]
I figured out how to do this. Should I submit a PR? I can include an option so that users can control whether enter exits the timer early, or whether it matches newlines.

**Comment by abo-abo** [comment]
Please PR.

**Comment by quicknir** [comment]
PR'ed #225 .
