### ISSUE TITLE
Describe `avy`'s package better

### ISSUE THREAD

**Issue by m1cm1c** [abo-abo/avy#221]
The current summary of `avy`'s package is "tree-based completion". The first paragraph of its description is:

> This package provides a generic completion method based on building
> a balanced decision tree with each candidate being a leaf.  To
> traverse the tree from the root to a desired leaf, typically a
> sequence of `read-key' can be used.

No one understands that this is `ace-jump-mode`'s successor. Honestly, this is worse than the notorious "Forward-port local commits to the updated upstream head".

When someone pointed me to `avy`, I at first assumed there to be a naming conflict and the wrong `avy` to have shown up in my packages list.

The first paragraph of `avy`'s `README.md` is a lot better, but `ace-jump-mode`'s "a quick cursor location minor mode for emacs" and

> It is a minor mode for Emacs. It can help you to move your cursor
> to ANY position in emacs by using only 3 times key press.

are **much** better still.

**Comment by abo-abo** [comment]
Suggestions?

**Comment by m1cm1c** [comment]
Instead of "tree-based completion", I'd choose: "Jump to arbitrary positions in visible text quickly."

Furthermore, I'd replace

> This package provides a generic completion method based on building
> a balanced decision tree with each candidate being a leaf.  To
> traverse the tree from the root to a desired leaf, typically a
> sequence of `read-key' can be used.
>
> In order for `read-key' to make sense, the tree needs to be
> visualized appropriately, with a character at each branch node.  So
> this completion method works only for things that you can see on
> your screen, all at once:

with:

> With Avy, you can move point to any position in Emacs – even in a different window – using very few keystrokes. For this, you look at the position where you want point to be, invoke Avy, and then enter the sequence of characters displayed at that position.
> 
> If the position you want to jump to can be determined after only issuing a single keystroke, point is moved to the desired position immediately after that keystroke. In case this isn't possible, the sequence of keystrokes you need to enter is comprised of more than one character. Avy uses a decision tree where each candidate position is a leaf and each edge is described by a character which is distinct per level of the tree. By entering those characters, you navigate the tree, quickly arriving at the desired candidate position, such that Avy can move point to it.
>
> Note that this only makes sense for positions you are able to see when invoking Avy. These kinds of positions are supported:

**Comment by abo-abo** [comment]
Please PR. I'd modify the header further to "Select visible text quickly.".
Also mind the 15 lines CA limit (unless you already have an Emacs CA).

**Comment by m1cm1c** [comment]
> Also mind the 15 lines CA limit (unless you already have an Emacs CA).

I have no idea what that means. Do you have a link describing that limit? I wasn't able to find anything online.

**Comment by m1cm1c** [comment]
I think I found out what it means. Will read up on it.

**Comment by m1cm1c** [comment]
According to https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html, that's only a rough limit. I modified 16 lines total, didn't replace everything, and took part of my changes from existing texts. I'd happily transfer the copyright to the FSF, but afaik that's not even possible where I live (Germany).
