### ISSUE TITLE
avy alternative to ace-jump-char-to-mode?

### ISSUE THREAD

**Issue by joe9** [abo-abo/avy#23]
Hello,

ace-jump-char-to-mode moves the cursor to a character before the jump point. (Similar to how 't' works in vim). Just want to check if there is any avy equivalent of that function?

Thanks

**Comment by abo-abo** [comment]
You want to jump to a character *before* the one that you have selected?  Why not select the one that you want in the first place?

**Comment by joe9** [comment]
good point, makes sense. Thanks.
