### ISSUE TITLE
[Feature Request] Shorter overlays closer to point

### ISSUE THREAD

**Issue by nverno** [abo-abo/avy#233]
This is a similar to #232, but related to sequence length. When calling `avy-goto-word-1` it would be nice if the closest candidates had the shortest sequences. For example, in the following text with the cursor at **|**

> aonsectetur adipisicing alit, aed ao aiusmod aempor ancididunt at
> aabore at aolore aagna aliqua. at animad ainim aeniam, auis
> aostrud axercitation **|** allamco
> 
> 

calling `avy-goto-word-1` `a` results in the [following options](https://imgur.com/a/ZaY3z), where notably the shortest key sequences are farthest from the cursor;.

**Comment by abo-abo** [comment]
Fixed in #242. Please test.
