### ISSUE TITLE
Feature request avy-action-zap-up-to-char and avy-action-zap-to-char

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/avy#234]
Similar to zap-to-char but with the ability to trigger off avy action

zap-up-to-char doesn't include the entered char
zap-to-char does include the entered char

Binding is flexible but these might work:
avy-action-zap-up-to-char  bind to 'z'
avy-action-zap-to-char  bind to 'Z'

**Comment by abo-abo** [comment]
Thanks, let me know what you think about the added one.

If there's nice a use case for the other one, I'll add it later, but I'd like to keep things simple.

**Comment by eflanigan00** [comment]
The added one works, thanks for adding it.
I really think we need both.

When I'm deleting backward I use zap-to-char (includes the character I'm deleting).

When I'm deleting forward I use zap-up-to-char (doesn't include the character)

Examples below:

1. My cursor is at C and I use zap-up-to-char to delete up to the word (including the whitespace) but not including the word. In the example I'm deleting up to description (but not including)

     This is my sentence and Cthere is some description

Results in

     This is my sentence and description

2. my cursor is at C then I use zap-to-char to delete This (including) 

     This is my sentence and Cthere is some description

Results in

     there is some description

If I had to pick only one I would prefer to have zap-up-to-char because of how I navigate files and edit. But that will change depending on the user.

**Comment by eflanigan00** [comment]
Another use case for zap-up-to-char is when using avy-goto-line.
The current implementation deletes the first character of the line the user specifies.
I would imagine that zap-up-to-char wouldn't have this problem.

**Comment by eflanigan00** [comment]
@abo-abo can you please add the other one also based on my comments above?

**Comment by abo-abo** [comment]
Will do. Is there a way to merge the two commands into one?

**Comment by eflanigan00** [comment]
I'm not sure. It is really 5 or 6 lines or code and to me having both makes sense but I could be overlooking something.

**Comment by abo-abo** [comment]
> overlooking something

We should try not to overlook the opportunity to simplify things. If one new command does the job of two old commands, it's a win.

For instance, you say:

- command-1 is useful if the target is after the point
- command-2 is useful if the target is before the point

So why not unify them into a single command-3 that uses the command-1 logic if the target is after the point and command-2 logic otherwise.

**Comment by eflanigan00** [comment]
@abo-abo would you be able to make this update easily?

**Comment by abo-abo** [comment]
Hi, sorry for the late response, I've had other things piling up. I'm coming back from vacation next week, I'll try to figure out this feature soon.

**Comment by eflanigan00** [comment]
No problem take your time. I hope you had a great vacation!

**Comment by eflanigan00** [comment]
@abo-abo any chance you can add this feature?

**Comment by abo-abo** [comment]
Sorry delaying. Yes, I'll add it eventually. But if I don't manage before this Friday, you'll have to wait until June; I have one more vacation coming up:)

**Comment by abo-abo** [comment]
OK, I've made a small modification that results in both of your use cases working. See also the commit message.

If you have more use cases that don't work currently, please open a new issue.

**Comment by eflanigan00** [comment]
This is amazing, thank you so much.
Have a great second vacation, you deserve it!!
