### ISSUE TITLE
Searching for in/visible points doesn't use invisibility property correctly

### ISSUE THREAD

**Issue by rnkn** [abo-abo/avy#237]
It appears that `avy--next-visible-point` and/or `avy—next-invisible-point` consider any text with the `invisible` text property to be invisible, and so exclude it from searching. However text is only invisible if the cdr of the `invisible` text property is included in the variable `buffer-invisibility-spec`.

Please see: https://www.gnu.org/software/emacs/manual/html_node/elisp/Invisible-Text.html

Reference: https://github.com/rnkn/fountain-mode/issues/85#issuecomment-383362701

**Comment by rnkn** [comment]
Bumping this as it means avy doesn't function in a lot more use cases than one might imagine.

**Comment by abo-abo** [comment]
Please provide a reproduction scenario. Some code regarding `buffer-invisibility-spec` was added to `avy--visible-p` in January this year.

**Comment by rnkn** [comment]
I don't use avy, it was causing issues for users of another package. If avy has since implemented with `buffer-invisibility-spec` as per the manual (linked above) then I'd say it's all good!

**Comment by abo-abo** [comment]
OK, I'll close the issue then. Thanks.
