### ISSUE TITLE
avy-goto-line fails with error in empty buffer

### ISSUE THREAD

**Issue by raxod502** [abo-abo/avy#238]
Steps to reproduce:

* Open `emacs -Q` and find an empty buffer.
* Run `M-x avy-goto-line`.
* Get error: `avy-goto-line: Wrong type argument: integer-or-marker-p, "zero candidates"`

This is because `avy--process` returns the text `"zero candidates"`, see also #130.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by raxod502** [comment]
Works great, thank you!
