### ISSUE TITLE
[PR] add avy-goto-end-of-line function

### ISSUE THREAD

**Issue by aqua36** [abo-abo/avy#241]
#240 

I think this function could be useful for some people, and thus is worth adding, It mirrors avy-goto-line behaviour and then jumps to the end of the line

Disclaimer: I'm very new to the open source world (especially the elisp part of it), so I don't know if my code meets the standards of your project and any pointers would be very much appreciated

**Comment by abo-abo** [comment]
Thanks, merged with some minor corrections. One minor suggestion is to improve your Git username and maybe email, but it's up to you.
