### ISSUE TITLE
[Feature Request] Show goto line overlay next to the first non whitespace character on the line

### ISSUE THREAD

**Issue by lane-s** [abo-abo/avy#243]
This is pretty self-explanatory from the title. Usually when I go to a line, I'm looking at the text on the line rather than all the way to the left side of the buffer where the overlay is displayed. I'm willing to hack on this, so I'll give it a go soon and report back.

This would be available as a configuration variable rather than the default.

**Comment by abo-abo** [comment]
It's pretty easy to do, patch `avy--line-cands`:

```diff
-(if (eq avy-style 'post)
-    (line-end-position)
-  (point))

+(if (eq avy-style 'post)
+    (line-end-position)
+  (save-excursion
+    (skip-chars-forward " \t")
+    (point)))
```

Please add a documented defcustom and PR.

**Comment by lane-s** [comment]
Added in fd7b9297191ebcd630310cdff7e78698eb81495c
