### ISSUE TITLE
Proposal: Option to have hints spell words out of chosen letters

### ISSUE THREAD

**Issue by Sevensidedmarble** [abo-abo/avy#248]
It's really hard both to parse and type 3-4 letter strings like "jqw" or "ffa" or "jal" very quickly. It's also hard to type them quickly. Your brain's really good at parsing and typing 2-5 letter words however.

Even if it adds more key strokes, I think there's some really interesting territory to expand upon here.

**Comment by ardpp** [comment]
Have you tried `(setq avy-style 'words)` ?

**Comment by Sevensidedmarble** [comment]
Well shoot. You guys rock. I didn't see that documented anywhere. Thanks!
