### ISSUE TITLE
checkdoc

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/avy#25]
I'd suggest running `M-x checkdoc` on the source code as there are a few problems here and there and packages in ELPA should generally be checkdoc compliant. 

There are some strange things in the docstrings, btw:

```el
(defun avy--goto (x)
  "Goto X.
X is (POS . WND)
POS is either a position or (BEG . END)."
  (if (null x)
      (message "zero candidates")
    (select-window (cdr x))
    (let ((pt (car x)))
      (when (consp pt)
        (setq pt (car pt)))
      (unless (= pt (point)) (push-mark))
      (goto-char pt))))
```

You shouldn't use uppercase to refer to anything but function params. `pos`, `wnd`, `beg`, `end` are all confusing in that sense. 

Same here:

```el
(defun avy--overlay-at (path leaf)
  "Create an overlay with STR at LEAF.
PATH is a list of keys from tree root to LEAF.
LEAF is ((BEG . END) . WND)."
```

There's no param `str`, which makes this docstring confusing for people used to the common conventions.

**Comment by abo-abo** [comment]
Thanks, STR used to be there. I factored it out at some point and forgot to update the doc.
