### ISSUE TITLE
in js2-mode, avy-goto-char-in-line cannot find all '/' in '/* */' or '/* foo */' or '/* foo */ bar /* foo */'

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/avy#252]
Neither can it find the first '/' in '*/ /*'. There are more permutations that I have run into but didn't take note of.

In my limited tests, the issue goes away after font-lock-mode is disabled. Turning font-lock back on may or may not have the issue again.

It also does not appear to be happening in C mode.

**Comment by abo-abo** [comment]
Please provide an example file.

**Comment by zhaojiangbin** [comment]
I narrowed it down to the `prettify-symbols-mode` and the particular font I am using for ligatures. The issue is actually not specific to js2-mode. It can happen in probably any major mode. I have it reproduced in js2-mode, text-mode, c++-mode and even fundamental-mode.

If it's too much of a trouble for you to set up and look into it, I can live with the issue not fixed. I am using Emacs 26.1 on macOS High Sierra, from https://emacsformacosx.com/:
"GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30"

I got the patched version of the Fira Code font and the lisp code for setup here: https://gist.github.com/reiver-dev/82da77ba3f0008c56624661a7375e0e8#file-ligatures-el

The processed font file can be found here: https://github.com/tonsky/FiraCode/files/1734878/FiraCode-private-area.zip

After the font is installed and font setup code loaded in Emacs, it is easy to reproduce the issue in an empty scratch buffer:
1. Run <kbd>M-:</kbd> `(ligatures-fira-code-setup)` and <kbd>M-x</kbd> `prettify-symbols-mode`.
2. Type in something like below in one line:
```
x /* y */ z
```
3. Run <kbd>M-x</kbd> `avy-goto-char-in-line`, then type '/'.

If you change major mode, you'll need to re-run `ligatures-fira-code-setup` and `prettify-symbols-mode` again.

This is what it looked like in my Emacs. The cursor was on 'y', only the first '/' was highlighted by key 'a':
<img width="163" alt="screen shot 2018-10-08 at 11 45 28" src="https://user-images.githubusercontent.com/4935788/46627557-b0fa7a80-caef-11e8-880e-28c079681d21.png">

**Comment by abo-abo** [comment]
You can try patching e.g. `avy--overlay-at-full` with:

```elisp
(setq beg (or (plist-get (text-properties-at beg) 'prettify-symbols-start) beg))
```

The overlay will be visible, but I don't think the result is satisfactory. 

It's probably better to just add an advice to disable `prettify-symbols-mode` before `avy-read` is called, and enable it back afterwards.

```elisp
(defun without-prettify-symbols (orig-fun &rest args)
  (prettify-symbols-mode -1)
  (let ((r (apply orig-fun args)))
    (prettify-symbols-mode 1)
    r))

(advice-add 'avy-read :around 'without-prettify-symbols)
```

**Comment by zhaojiangbin** [comment]
The advice works great. Thanks very much.

**Comment by abo-abo** [comment]
You're welcome.
