### ISSUE TITLE
add key-bindings like p,n to navigate over the candidates.

### ISSUE THREAD

**Issue by beacoder** [abo-abo/avy#254]
Is it possible to add keybindings to navigate highlighted candidates, for instance: use p as previous,n as next.
I know that currently, when avy find out several candidates, it identified each with a different key or keys.
I suggest we exclude keys like "p","n". so that when user print "p","n", user can do quick navigation like previous or next instead of current behavior.
thanks a lot.

**Comment by abo-abo** [comment]
Thanks, please test.
