### ISSUE TITLE
`(wrong-type-argument listp t)`

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/avy#264]
I installed an update to `avy` today and now, I sometimes, though not always, get a `wrong-type-argument` error with `avy-goto-word-or-subword-1`. This is the backtrace I get with `debug-on-error` set to `t`:

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  assoc(t t)
  avy--visible-p(99)
  avy--next-invisible-point()
  avy--find-visible-regions(1 3989)
  avy--regex-candidates("\\ba" nil nil)
  avy--generic-jump("\\ba" nil nil nil)
  avy-goto-word-1(97 nil)
  funcall-interactively(avy-goto-word-1 97 nil)
  call-interactively(avy-goto-word-1)
  avy-goto-word-or-subword-1()
  funcall-interactively(avy-goto-word-or-subword-1)
  call-interactively(avy-goto-word-or-subword-1 nil nil)
  command-execute(avy-goto-word-or-subword-1)
```

Looking at the source for `avy--visible-p`, the problem seems to arise from the fact that `buffer-invisibility-spec` is set to `t`.

Do you know if this may be a problem with my configuration, or is this a bug?

**Comment by abo-abo** [comment]
This was a bug related to the new improvement in #264. Should be fixed now, thanks.

**Comment by joostkremers** [comment]
Yes, it's fixed. Thanks!
