### ISSUE TITLE
Add filter argument to `avy-jump`

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [abo-abo/avy#267]
I see that `avy--regex-candidates` has the potential to use a filter to control which of the candidates we want and don't want. However, this filter is not available to `avy-jump`. I had to use advice to override `avy-jump` just so I could add one. 

I propose adding an argument `filter` to `avy-jump` so it would look like this:

```
(cl-defun avy-jump (regex &key window-flip beg end action filter)
  (setq avy-action (or action avy-action))
  (let ((avy-all-windows
         (if window-flip
             (not avy-all-windows)
           avy-all-windows)))
    (avy--process
     (avy--regex-candidates regex beg end filter))))
```

**Comment by abo-abo** [comment]
Thanks.
