### ISSUE TITLE
avy-goto-line doesn't work w/ lines beginning with org-links in org-mode

### ISSUE THREAD

**Issue by mac230** [abo-abo/avy#269]
Small issue, possibly related to:

https://github.com/abo-abo/avy/issues/261

With org-mode enabled, avy-goto-line doesn't allow you to select lines that begin with a link (although web links work).  No such issue in non-org major modes.  Simple example below:

```emacs-lisp
some text                                  ;; can select this line
https://github.com/abo-abo/avy/issues/261  ;; can select this line
a link -> [[~/foo.txt][foo]]               ;; can select this line
[[~/foo.txt][foo]]                         ;; can't select this line
```

Any help much appreciated.  Thanks

**Comment by abo-abo** [comment]
Can't reproduce. Please try with `emacs -Q`.

**Comment by mac230** [comment]
Yep, can't reproduce with emacs -Q.  Sorry for not trying that prior to posting.

**Comment by abo-abo** [comment]
No problem.

**Comment by mac230** [comment]
I tracked this to having org-mode and visual-line-mode enabled simultaneously.  With one or the other off, avy-goto-line works for org-links.

**Comment by abo-abo** [comment]
This is due to the (questionable) behavior of `line-move-visual`:

    some text                                  ;; can select this line
    https://github.com/abo-abo/avy/issues/261  ;; can select this line
    1a link -> [[~/foo.txt][foo]]               ;; can select this line
    [[~/foo.txt][2foo]]                         ;; can't select this line

It will move the cursor from `1` to `2`, instead to the beginning of the line.

Should be fixed now, thanks.

**Comment by mac230** [comment]
Works great; thank you very much for the fix.
