### ISSUE TITLE
Flyspell misspelled words in org-mode links break avy-mode

### ISSUE THREAD

**Issue by michaelmhoffman** [abo-abo/avy#271]
To reproduce:

1. ```(flyspell-mode t)```

2. Create `test.org` with the following contents:

```
* correct
* [[link][incxrrect]]
* correct
* [[link][incorr3ct]]
* correct
```

3. Move the cursor over the incorrectly spelled words to ensure they get Flyspell's wavy red underline.

4. `(avy-goto-char ?r)`

The only `r`s that are marked are before the first misspelled word, or in subsequent misspelled words, as seen in screenshot:

![image](https://user-images.githubusercontent.com/13810027/56895493-4131ea00-6a57-11e9-8bac-9cb869e5f990.png)

**Comment by michaelmhoffman** [comment]
`(avy--find-visible-regions (point-min) (point-max))` returns `((1 . 30) (53 . 76))`.

30 is the newline after `incxrrect`
53 is the `i` in `incorr3ct`
76 is the end of buffer

Expected: `((1 . 76))`

That is the output I get when I have `flyspell-mode` disabled.

**Comment by abo-abo** [comment]
For me, (avy--find-visible-regions (point-min) (point-max)) returns `((1 . 13) (21 . 30) (32 . 45) (53 . 62) (64 . 75))`.

So I can't reproduce the bug.

**Comment by abo-abo** [comment]
Tried `make run` from this repository that launched `emacs-26.1 -Q`. Still can't reproduce.

**Comment by michaelmhoffman** [comment]
Here's a more straightforward test case. I'm using the latest avy from MELPA stable (0.4.0) but can try with the repo version.

1. Create `test.el` in same direction as `test.org`:

```
(require 'package)
(setq package-load-list
      '((avy "0.4.0")))
(package-initialize)

(find-file "test.org")
(flyspell-mode t)

(redisplay)
(flyspell-buffer)

(avy-goto-char ?r)
(message "%s" (avy--find-visible-regions (point-min) (point-max)))```

2. `emacs-26.2 -Q -l test.el`

I get:

![image](https://user-images.githubusercontent.com/13810027/57479527-9fd34100-726b-11e9-9b4e-20cbbdc2c218.png)

3. Type `a`

Output: `((1 . 30))`

**Comment by michaelmhoffman** [comment]
Tested on commit a7230906c44a1da78e1405f3694f1e61f43043dc and it works as expected. Please feel free to close.

Could we have a new melpa-stable version with this fix please? :smile: 

Thanks again for your work on this useful package and sorry for the confusion.

My script for testing in the avy repo is below for posterity:

```
(add-to-list 'load-path ".")
(require 'avy)

(find-file "test.org")
(flyspell-mode t)

(redisplay)
(flyspell-buffer)

(avy-goto-char ?r)
(message "%s" (avy--find-visible-regions (point-min) (point-max)))
```

**Comment by abo-abo** [comment]
Thanks.
