### ISSUE TITLE
Avy-resume issue with avy-goto-chat-timer

### ISSUE THREAD

**Issue by Ergus** [abo-abo/avy#277]
I use most of the time avy-goto-chat-timer and I have noticed that after using it, if I call avy-resume I get prompted asking for a char instead of resuming avy with the previous candidates (As it happens in all the other ccommands). Is this an issue or avy-goto-chat-timer cannot be resumed as all the other commands I have tried?

**Comment by abo-abo** [comment]
Thanks, please test.
