### ISSUE TITLE
Odd behaviour with avy-goto-word-1

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/avy#28]
See the [screenshot](https://www.dropbox.com/s/le7rn7dznwjkgfj/Screenshot%202015-05-09%2013.08.00.png?dl=0).

Why are they no two-char leads? Looking at the screenshot from the README this shouldn't be the behaviour.

**Comment by abo-abo** [comment]
It appears that you're using `'at` overlay style, see `avy-goto-char-style`. Does it still work?

**Comment by bbatsov** [comment]
Yep. Both the word and the char styles are set to `'at`. Seems to me that this should affect whether all visible windows have a background overlay or not.

**Comment by bbatsov** [comment]
Forget what I said - thought I was commenting on another ticket.

So, I'd like to see multiple lead characters even when using `'at`.

**Comment by abo-abo** [comment]
Fine, use `at-full`.

**Comment by bbatsov** [comment]
Thanks for adding this!

Btw, you might want to make those description a bit longer - if I didn't see this at another ticket I might have had hard time figuring out how to change this.
