### ISSUE TITLE
avy-isearch doesn't respect isearch case sensitivity

### ISSUE THREAD

**Issue by cyberthal** [abo-abo/avy#280]
avy-isearch doesn't respect isearch case sensitivity

if the isearch-forward is case sensitive and finds only one match, but multiple case-insensitive matches exist, avy-isearch will ask the user to choose between the case-insensitive matches.

**Comment by cyberthal** [comment]
Just found avy-case-fold-search. That will work. It's a bit unexpected to have avy-isearch vary from its normal behavior when isearch has only one match. Maybe it should follow isearch's case sensitivity instead in this instance. I don't know, so I won't close this myself.

**Comment by abo-abo** [comment]
Thanks, please test.
