### ISSUE TITLE
avy-goto-char-timer: jump to unique combination

### ISSUE THREAD

**Issue by weeTC** [abo-abo/avy#284]
Assuming that the idea of avy is to jump to character combinations that can be seen, why does avy-goto-char-timer wait for the timer even when there is already only one instance?

**Comment by abo-abo** [comment]
It's been this way since it was implemented. I guess the extra utility is that you can back out of a unique result by using backspace. Let's keep it the way it is.  If it's really bothering you, please PR with a new defcustom that does what you want.

**Comment by agenbite** [comment]
In case someone falls here and wants to save themself some looking around, it seems there's `‎avy-single-candidate-jump` after all, which you can set to `t` if you want what the OP did. It'd be nice to add it to the docs (or buy me a pair of glasses if it's already there).

**Comment by smahm006** [comment]
Actually came here for the opposite. I want to not jump to an exact candidate so I can do some action on it before jumping so setting avy-single-candidate-jump to nil works for me
