### ISSUE TITLE
Fix wiki for avy-case-fold-search

### ISSUE THREAD

**Issue by th994** [abo-abo/avy#291]
Added behavior when avy-case-fold-search value is set to nil on wiki. Also, the case-fold-search link was disabled, so it was fixed. The link of the revised wiki is as follows.

https://github.com/th994/avy-wiki/blob/master/defcustom.org

**Comment by abo-abo** [comment]
The wiki is open to public edits, there's no pre-commit review. Just make the change directly, and I'll have a look later. Thanks.

**Comment by th994** [comment]
Thank you for your reply. I fixed it.

**Comment by abo-abo** [comment]
Thanks.
