### ISSUE TITLE
[Smart case] For precise movements that further narrow possible jump locations

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [abo-abo/avy#295]
Hello,

I'd like to propose to change **case insensitive search** that highlights all possible jump locations to **smart case search** that has the following behavior:
* If the search string has **only lowercase characters**. perform **case insensitive search** (already implemented)
* If the search string contains **uppercase characters**, perform **case sensitive search**

Smart case search allows to be more precise in jumping around by further narrowing possible jump locations

**Comment by abo-abo** [comment]
What exactly do you mean by search? `avy-goto-char-timer`?

Because we have `avy-case-fold-search` for `avy-goto-char`.

**Comment by volodymyrprokopyuk** [comment]
Hello,

Yes, I mean the `avy-goto-char-timer`.

I have the below Avy configuration
```elisp
(add-to-list 'load-path "~/.emacs.d/avy")
(require 'avy)
(global-set-key (kbd "M-j") 'avy-goto-char-timer)
```
How can I get smart case search described above for the `avy-goto-char-timer` case?

**Comment by abo-abo** [comment]
You should set:

```elisp
(setq avy-case-fold-search nil)
```

`avy-goto-char-timer` calls `avy--read-candidates`, which will behave as you described when `avy-case-fold-search` is set to nil.

**Comment by volodymyrprokopyuk** [comment]
Hello,

Worked like a charm!

Thank you very much!

**Comment by Hi-Angel** [comment]
> ```emacs-lisp
> (setq avy-case-fold-search nil)
> ```

I should note though, the `avy-case-fold-search` documents a different behavior, it says setting it to `nil` makes it case-sensitive. Which btw is what I'm interested in: is there a way to make searches case-sensitive?

**Comment by Hi-Angel** [comment]
> > ```emacs-lisp
> > (setq avy-case-fold-search nil)
> > ```
>
> I should note though, the `avy-case-fold-search` documents a different behavior, it says setting it to `nil` makes it case-sensitive. Quote:

> ```elisp
> (defcustom avy-case-fold-search t
>   "Non-nil if searches should ignore case."
>   :type 'boolean)
> ```

Which btw is what I'm interested in: is there a way to make searches case-sensitive?

**Comment by Hi-Angel** [comment]
Although I stand corrected, the sentence `"Non-nil if searches should ignore case."` is vague, and can imply any behavior for `nil` value.
