### ISSUE TITLE
avy-goto-line: Wrong type argument: integer-or-marker-p, nil

### ISSUE THREAD

**Issue by duianto** [abo-abo/avy#299]
#### Problem
Canceling `M-x` `avy-goto-line` `RET` with `ESC`
shows the error message:
>avy-goto-line: Wrong type argument: integer-or-marker-p, nil

Enabling `M-x` `toggle-debug-on-error` `RET`
And reproducing the issue shows:
>Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  avy-action-goto(nil)
  avy-goto-line(1)
  funcall-interactively(avy-goto-line 1)
  call-interactively(avy-goto-line)
  evil-avy-goto-line(nil)
  funcall-interactively(evil-avy-goto-line nil)
  call-interactively(evil-avy-goto-line nil nil)
  command-execute(evil-avy-goto-line)

#### Cause
The function `avy-action-goto` receives: `nil`
(the second error line shows: `avy-action-goto(nil)`)
it then tries to call: `(goto-char nil)`

source: https://github.com/abo-abo/avy/blob/cf95ba9582121a1c2249e3c5efdc51acd566d190/avy.el#L681

which results in the error: `(wrong-type-argument integer-or-marker-p nil)`

#### Notes
It works fine to cancel other avy commands with `ESC`.

#### System Info

avy-20191106.1234
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
Windows 1903

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by duianto** [comment]
Confirmed, there's no error message with: `avy-20200311.1106`, Thanks.
