### ISSUE TITLE
Support a 'overwrite' decision char overlay flavor

### ISSUE THREAD

**Issue by YangZhao11** [abo-abo/avy#30]
I very much like the idea to display all subsequent keys needed for the decision. The existing pre and post style of displaying these inserts these decision chars, which push original text rightwards.

Can we please have a style that overwrites at jump location, so that underline text does not change location? The way I use it is to look at the location I want to jump to, then issue the jump command; if the location changes in this process I need to scan to find my desired location again, which could be annoying.

Thanks for the awesome work in the first place!

**Comment by abo-abo** [comment]
Use the new `at-full` style.

**Comment by bbatsov** [comment]
To elaborate on this a bit - `(setq avy-style 'at-full)`.

**Comment by YangZhao11** [comment]
Wow. such speed :) Thanks alot!
