### ISSUE TITLE
Transition from avy-goto-char-timer to search command

### ISSUE THREAD

**Issue by noctuid** [abo-abo/avy#303]
Would be nice if on failure `avy-goto-char-timer` did something like return the input string, so that a command could be created around it that opens swiper, for example, if there is no match in the visible buffer.

**Comment by abo-abo** [comment]
Thanks. The return result of `avy-goto-char-timer` is either a cons cell or `t`. We could theoretically use `buffer-substring` to get the text from the cons cell, but I've added a variable as well for convenience.

**Comment by noctuid** [comment]
Awesome, thanks!
