### ISSUE TITLE
avy-orders-alist does not work with avy-goto-line

### ISSUE THREAD

**Issue by exp2ipi** [abo-abo/avy#307]
I was looking for a way to obtain avy-goto-line behavior described in #232, and as suggested tried using `avy-orders-alist`, however the following results in an error being thrown when `avy-goto-line` is invoked: `(add-to-list 'avy-orders-alist '(avy-goto-line . avy-order-closest))`.  

The behavior in question would be desirable as a universal way to navigate by lines relative to the current point, particularly in visual-line-mode.

Edit: it turns out that the visual-line behavior I am looking for is implemented by `evilem-motion-{next,previous}-visual-line`.  I'll leave you to decide whether the error behavior I've observed is a bug or not.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by exp2ipi** [comment]
Thanks, works
