### ISSUE TITLE
key binding "C-:" for avy-goto-char doesn't work

### ISSUE THREAD

**Issue by choyoungcin** [abo-abo/avy#308]
add a key-binding in emacs init file:
```(global-set-key (kbd "C-:") 'avy-goto-char)```
for avy-goto-char function. 

When I press down **Ctrl** and **:(with Shift pressed)**, nothing happens.
But when use **Meta-x avy-goto-char**, the commands list window shows **C-:** already bound to this function. And this function works well.

And if I replace char **:** to **j** (for example), it works fine.
Please help

**Comment by abo-abo** [comment]
It seems you're using Emacs inside a terminal. Emacs cannot recognize the <kbd>C-:</kbd> sequence when inside the terminal. I suggest using GUI Emacs to overcome this.

**Comment by choyoungcin** [comment]
Many thanks
