### ISSUE TITLE
Feature: avy transpose lines

### ISSUE THREAD

**Issue by LaurenceWarne** [abo-abo/avy#310]
Essentially, the function allows the user to select two lines from the currently active region and then transposes them, continuing to do this until the user quits out.

Demo (apologies for quality):

![avy-demo-optimised](https://user-images.githubusercontent.com/17688577/87328703-cd7ddf00-c52d-11ea-8d7b-8df797bace57.gif)

I pretty much have the functionality down so I can PR for this if you want to incorporate this feature.

Thanks.

**Comment by a13** [comment]
> I pretty much have the functionality down so I can PR for this if you want to incorporate this feature.

do you have FSF copyright assignment signed?

**Comment by LaurenceWarne** [comment]
> > I pretty much have the functionality down so I can PR for this if you want to incorporate this feature.
> 
> do you have FSF copyright assignment signed?

Happy to PR and fill out the request form if it will help getting this feature request looked at. I haven't yet filled out the request form, it seemed to me when I looked at it that it worked on the assumption that a change had been agreed already.
