### ISSUE TITLE
Replace avy-init.el with a setup section in the README

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/avy#32]
Seems to me this file has very little value - I'd suggest simply placing it's contents in "a manual setup" section of the README. Might also be worth mentioning installation from MELPA & ELPA.

**Comment by abo-abo** [comment]
The file is used for `make compile` and `make run`. It can be excluded from MELPA though, since the Makefile isn't installed anyway.

**Comment by bbatsov** [comment]
I think it'd be better if you added this conditionally to the tests.

**Comment by abo-abo** [comment]
What do you mean?

**Comment by bbatsov** [comment]
Have a look [here](https://github.com/bbatsov/projectile/blob/master/test/run-tests).

**Comment by bbatsov** [comment]
On a general note - it always a good idea to keep test stuff in a separate folder. Makes it clearer what is what.

**Comment by abo-abo** [comment]
Actually, I like a flat directory structure, especially if there are so few files. A lot more efficient.
