### ISSUE TITLE
Handle apostrophes as word delimiters

### ISSUE THREAD

**Issue by bbatsov** [abo-abo/avy#34]
Right now we you have something like `O'Conner`, Conner is not treated like a word start. Seems reasonable to split words at apostrophes even for things like `we'll`, `he's`, as those are technically two words anyways.

**Comment by abo-abo** [comment]
I prefer to stick to how Emacs defines a word: with `\\b`. `avy-goto-word-1` can be used in many modes, saying that `'` starts a word boundary introduces overhead and workarounds and other bad things.  It's best to just rely on `\\b`.
