### ISSUE TITLE
Unreachable places

### ISSUE THREAD

**Issue by acml** [abo-abo/avy#35]
With the following buffer content i can not jump to anywhere except the first capital T.

//Text
//Text
//Text
//Text

**Comment by abo-abo** [comment]
Can't reproduce. Both `avy-goto-char` and `avy-goto-word-1` work fine. What command are you using, anyway?

**Comment by acml** [comment]
Sorry, my mistake. I was running command avy-goto-word-1 instead of avy-goto-char.
