### ISSUE TITLE
avy-goto-line: display problem with leading tabs and the at-full style

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/avy#43]
1. Set the `at-full` as style for `avy-goto-line`.
2. Input two lines of text in a text mode buffer - the first line starting with a tab (entered with `C-q C-i`) then any non-white space text, second line starting with 8 spaces followed by any non-white spaces.
3. `M-x avy-goto-line`, note the non-white space text in the first line jumped to the left.

![screen shot 2015-05-16 at 8 12 18 pm](https://cloud.githubusercontent.com/assets/4935788/7668869/e7acfa86-fc07-11e4-9479-d2d3d45a4e9d.png)

![screen shot 2015-05-16 at 8 08 43 pm](https://cloud.githubusercontent.com/assets/4935788/7668868/ce6c774a-fc07-11e4-87d3-9e60d30067dc.png)

It also shows up in a magit-status buffer with unstaged or staged items which are indented with tabs.

**Comment by abo-abo** [comment]
Thanks.
