### ISSUE TITLE
avy-all-windows functionality broken

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/avy#45]
Setting avy-all-windows to t is ineffective. Now it shows the jump locations only in the current window regardless.

Also, can you suggest how I can get this functionality without using call-interactively?

```el
(defun my/avy (arg)
      "
        `my/avy' -> `avy-goto-word-1'
    C-u `my/avy' -> `avy-goto-char-2'
C-u C-u `my/avy' -> `avy-goto-line'
"
      (interactive "p")
      (let ((avy-all-windows t) ; search in all windows
            (fci-state-orig fci-mode)
            (fn (cl-case arg
                  (4  'avy-goto-char-2) ; C-u
                  (16 'avy-goto-line) ; C-u C-u
                  (t  'avy-goto-word-1))))
        (if fci-state-orig
            (fci-mode 'toggle))
        (funcall fn)
        (if fci-state-orig
            (fci-mode 'toggle))))
```

The above wrapper function breaks because now the first arg to `avy-goto-word-1` is a manadatory arg `char`; earlier its only arg was an optional arg to toggle `avy-all-windows`.

I cannot use `call-interactively` because then my wrapper function arg gets passed on to the function I am calling interactively.

**Comment by abo-abo** [comment]
Sorry, I changed the `defcustom` and forgot to update `avy-window-list`. Please check if it works fine now.
