### ISSUE TITLE
RFE/Usability suggestion: dim text on selection and show letters over the text to be selected

### ISSUE THREAD

**Issue by jsynacek** [abo-abo/avy#48]
I like the plugin, but what makes it very hard for me to use is that all the text that is to be selected gets moved, because the shortcut letters are written in front of it. To make things more usable, I suggest to put the shortcut letters over the text. Dimming all other text would also be nice.

What I'm basically asking for is http://vimawesome.com/plugin/easymotion, which I consider the ultimate jumping plugin there is.

**Comment by abo-abo** [comment]
This is all supported. Just check [the docs](https://github.com/abo-abo/avy/wiki/defcustom).

The setting you're looking for:

```elisp
(setq avy-background t)
(setq avy-style 'at-full)
```

**Comment by jsynacek** [comment]
I should have checked the docs more thoroughly... Thanks!

On Wed, May 20, 2015 at 11:08 AM, Oleh Krehel <notifications@github.com>
wrote:

> This is all supported. Just check the docs
> <https://github.com/abo-abo/avy/wiki/defcustom>.
>
> The setting you're looking for:
>
> (setq avy-background t)
> (setq avy-style 'at-full)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abo-abo/avy/issues/48#issuecomment-103818624>.
>



-- 
Jan Synáček
