### ISSUE TITLE
Jumping using avy-goto-word across frames does not select the destination frame

### ISSUE THREAD

**Issue by Mike--F** [abo-abo/avy#54]
When jumping across frames, point seems to have been moved to the destination frame, however the frame does not seem to be active and is not brought to the front of other frames.  After jumping running commands that move point such as forward-char do nothing.

In the attached screen shot I have just used avy-goto-word-1 to jump to the frame on the left at the when command.  You can see that the frame was not brought to the foreground.

I have customized this way:

'(avy-all-windows (quote all-frames))

Thanks
Mike

![new microsoft powerpoint presentation](https://cloud.githubusercontent.com/assets/5657608/7894755/fb1c4ae4-0635-11e5-983a-ee6db008c4ed.jpg)

**Comment by abo-abo** [comment]
Thanks.

**Comment by Mike--F** [comment]
Seems fixed.

Thanks
Mike
