### ISSUE TITLE
Allow users to customize what to jump to with avy

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/avy#55]
It would be useful for user to customize what to jump to. For example, a user can create an avy command to jump to all the `if` occurrences; similar `while`, `for`... so I can bind all of them under some prefix key like `C-j` and quickly jump to with a few key strokes with minimal screen disruption.

I got the idea from this issue: https://github.com/abo-abo/lispy/issues/77

**Comment by PythonNut** [comment]
Would this be something that should be built into `avy`? You could achieve this yourself with a small snippet:
```emacs
(defun avy-goto-while ()
  (interactive)
  (avy--goto
    (avy--process
      (mapcar
        (lambda (point)
          (cons (cons point point)
            (get-buffer-window)))
        (let ((points))
          (save-excursion
            (goto-char (window-start))
            (while
              (prog1
                (search-forward "while"
                  (min (point-max) (window-end))
                  t)
                ;; adjust target to beginning of match
                (push (- (point) 5) points)))
            points)))
      (avy--style-fn avy-style))))
```

**Comment by abo-abo** [comment]
Even simpler:

    (avy--generic-jump "while" nil 'pre)

**Comment by tuhdo** [comment]
@abo-abo Great to know that it's just that simple. Maybe you could provide a macro that wraps around `avy--generic-jump`: a user can use this macro to define his jump command to a particular regexp. For example, let's name this macro `avy-def-jump`. A user can use it like this:

```elisp
(defvar avy-while-object '("while " nil 'pre))
(avy-def-jump global-map (kbd "C-j w") 'avy-while-object)
```
Then it generates appropriate binding for a particular keymap.

**Comment by tuhdo** [comment]
It's great that `avy` already accepts regexp. Now I can jump to any conditional sexp in Lisp with this simple snippet:

```elisp
(avy--generic-jump "(if\\|(cond\\|(when\\|(unless" nil 'pre)
```
So now instead of thinking about jump to a character, I can think about jump to semantic units on screen!

I think this is a great feature that should be mentioned on `avy` homepage. Now we only need a macro for ease customization.

**Comment by abo-abo** [comment]
> Now we only need a macro for ease customization.

A macro unnecessarily restricts the things you can do:

- naming
- documenting
- advising
- re-using
- calling by name

It's only worth it if the abstraction power is high, which it isn't in this case.  This is much better in my opinion, and not much longer:

```elisp
(global-set-key
 (kbd "C-j w")
 (defun avy-goto-while ()
   (interactive)
   (avy--generic-jump "while " nil 'pre)))
```

**Comment by tuhdo** [comment]
But then, new users will have to write boilerplate code like that. I am assuming `avy` users are non-Elisp programmers as well.

But that's look fine to me. I think this could be turned into a feature, and provide a few built-in commands for popular major modes i.e. C/C++, Python, Lisp
