### ISSUE TITLE
Ignore windows displaying buffers of certain modes

### ISSUE THREAD

**Issue by tsdh** [abo-abo/avy#57]
I just had the strange situation that I wanted to jump to a } in my tex document, and although there were only 15 matches visible, I got avy key sequences of length four!

Well, the reason was that I had two windows with two buffers.  One buffer showed my tex document, the other showed the corresponding PDF file using [PDF Tools](https://github.com/politza/pdf-tools).  The problem was that in addition to the 15 occurrences of } in my tex document window, there were several hundreds of matches in the "visible portion" of the PDF buffer.

It doesn't make sense to consider matches in such a PDF buffer because PDF contents are garbage from a human perspective, and the actual contents aren't visible anyway because they are overlayed with an image showing the rendered version of the PDF's current page in terms of the `display` text property.

So I'd suggest to have some `avy-ignored-modes` variable where users can add major mode symbols and buffers using these modes shouldn't be considered when finding matches.  Obvious candidates to be put on that list by default are all kind of modes for binary data which is then displayed in a human-friendly way, e.g., `image-mode`, `doc-view-mode`, `pdf-view-mode` (from PDF tools), etc.

**Comment by abo-abo** [comment]
> So I'd suggest to have some avy-ignored-modes variable where users can add major mode symbols and buffers using these modes shouldn't be considered when finding matches. Obvious candidates to be put on that list by default are all kind of modes for binary data which is then displayed in a human-friendly way, e.g., image-mode, doc-view-mode, pdf-view-mode (from PDF tools), etc.

There's already a work-around in place for `doc-view-mode` and `image-mode`. I'll add `pdf-view-mode` now.

**Comment by tsdh** [comment]
Ah, I see.  But I think it would be good to have that list as a customize option.  We can never know about all such modes, and some of them might even be private.  And of course there might also be different user preferences, e.g., some users might want to avy-jump also in `hexl-mode` buffers while others might not.

**Comment by abo-abo** [comment]
> And of course there might also be different user preferences, e.g., some users might want to avy-jump also in hexl-mode buffers while others might not.

Makes sense. Added customization.
