### ISSUE TITLE
Avy-background-face seems not applied on avy-goto-line?

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/avy#60]
### Situation:

After calling `customize-face`, then I search for `avy-background-face`.

The foreground and the background faces are changed, and this is saved and set in the current and future sessions. The colors are visible in the customization window.

### Issue:

When I call `avy-goto-line`, then I still get another colors in the backgroud.

Does the face of `avy-goto-line` not belonging to the group of `avy-background-face`?

Thanks in advance.

**Comment by abo-abo** [comment]
> Does the face of avy-goto-line not belonging to the group of avy-background-face?

The background doesn't work for `avy-goto-line` on purpose. I thought that since the location of the decision chars is known in advance, there's no reason to dim the whole window. Are you sure you want it to work?

**Comment by ReneFroger** [comment]
It's not clear to me what you mean with dim the whole window. I made a screenshot to illustrate my point

![Uploading Untitled.png…]()

As you can see, the background face of the decisions chars is pinky. I would like to change that. Does any face exists to customize with it?

**Comment by abo-abo** [comment]
You want to customize `avy-lead-face`. `avy-background-face` is responsible for dimming the whole window, you don't want that one.

**Comment by ReneFroger** [comment]
Then I'm was wrong. I assumed avy-background-face was for the hinting characters.

Thanks for your help, it's really appreciated. And what a nice weather you have in Eindhoven! :wink:.
