### ISSUE TITLE
avy-goto-line and avy-isearch ignore avy-styles-alist (and avy-style)

### ISSUE THREAD

**Issue by tprk77** [abo-abo/avy#61]
I just tried setting `avy-styles-alist` to `'at-full` for `avy-goto-line`, and it didn't work.

(I realize that setting `avy-goto-line` to `'at-full` may sound a little weird, because then you can't see the begining of the line... but I personally don't like the text moving around so much. And anyway, I've usually already read the beginning of the line when I start the command.)

Anyway, I started looking at the code, and I noticed that `avy-goto-line` and `avy-isearch` have their styles hardcoded to `'pre` and `post`, respectively.

Are you receptive to a patch? I can do a pull request if you want. I can also try to add some code so the default style for these functions is preserved.

Thank you for this extension!

**Comment by abo-abo** [comment]
> Are you receptive to a patch? I can do a pull request if you want. I can also try to add some code so the default style for these functions is preserved.

Sure. Just don't forget to use `avy--with-avy-keys`: it sets `avy-style` for particular command.

**Comment by tprk77** [comment]
Ah, so `avy-goto-line` was already fixed in master (by a39f689908160e4f3c9e62e2b17c7b774f2949ac). My code was a bit out of date. Anyway, I still did a quick fix for `avy-isearch`.
