### ISSUE TITLE
Idea: enlarge the possible values of avy-keys to actual keys and not only chars

### ISSUE THREAD

**Issue by tsdh** [abo-abo/avy#66]
Being a bad typist, I'm still not using avy as efficient as I'd like to.  The problem is that if I'm supposed to enter a key sequence which I'm not already used to (like writing actual words), chances are good that I do a typing error.

But there are key sequences which even I am able to type without any issues, e.g., `up down left left`.  So what I'd like to be able is to use all the keys my keyboard provides as `avy-keys`.  Basically, I'd use the arrow keys and maybe some adjacent keys like `prior` and `next` on my laptop.

As far as I can see, this would involve only few changes to avy:

1. avy would need to use `read-key` instead of `read-char` for reading the keys from a user when selecting the jump target (and have a special case so that `C-g` calls `keyboard-quit` instead of considering it a valid jump key).
2. avy would need an alist which defines a printable representation of non-character keys that are used for the overlays. For example, ▲, ▼, ◀, ▶, △, ▽ seem to be nice candidates for the arrow keys and `prior` (PageUp) and `next` (PageDown).

To me, this feature is kind of related to `avy-translate-char-function` which allows to type, e.g., `SPC` as an alternative to `a`.  But with `avy-keys` allowing arbitrary keys, you could use `SPC` in the first place (with representation _), so that translation wouldn't really be needed.

Does that sound reasonable?  I'm happy to implement this feature.  But I'm off on holidays for a week starting tomorrow, so it might take some time.  But of course I'm far from opposed if someone else volunteers. ;-)

**Comment by abo-abo** [comment]
> Does that sound reasonable? I'm happy to implement this feature. But I'm off on holidays for a week starting tomorrow, so it might take some time. But of course I'm far from opposed if someone else volunteers. ;-)

The feature seems reasonable. But for me, it's a lot of effort for little payoff. If you like to implement it - go ahead, there's no rush.  Or maybe I'll do it when I get bored and there's nothing else to do :)

**Comment by tsdh** [comment]
I'll start working on this now.

**Comment by abo-abo** [comment]
So you've fixed this one, thanks again.
