### ISSUE TITLE
Confusing avy-lead-faces variable

### ISSUE THREAD

**Issue by ilohmar** [abo-abo/avy#68]
Maybe it's just me, but with `avy-lead-faces` I no longer understand how to achieve the decision-path highlighting I like (despite quite some testing).

I am using the at-full style at the moment, but will formulate things so that they should equally apply to the pre style: I would like the *first typable* char of each decision path to appear in one face (say bold inverse), and all the remaining ones in another face (however many there are, and that differs between different paths).  (Not essential: When using the pre style, I would like to dim out the chars I have already typed.) Could anybody help me achieve this?

Things briefly worked for me personally after you introduced `avy-highlight-first` in #42.  But with the arrival of `avy-lead-faces` I found it hard to even understand the intent.  As far as I can tell, the faces therein are used one after another, but the first applies to the *last* chars in the paths, the second to the last-but-one etc.  With this setup I cannot get the desired result I describe above.  Also I do not understand if `avy-highlight-first` is still supposed to have an effect (which one?  under what conditions?).

**Comment by abo-abo** [comment]
> But with the arrival of avy-lead-faces I found it hard to even understand the intent.

The intent is for you to have the idea of the current depth you're in. You can easily determine how many more chars you have to type by just looking at the background of the first char.

I'll see if I can make it more customizable at some point. In the end, you can just implement your own version of `avy--overlay-at-full` that works exactly how you want.

**Comment by ilohmar** [comment]
Ok, thanks for you reply.  I will probably write such a private version then, for the time being.  If anything more generally useful comes out of it, I'll open a PR.
