### ISSUE TITLE
`avy-pop-mark`?

### ISSUE THREAD

**Issue by endrebak** [abo-abo/avy#69]
`ace-jump` has this wonderful feature where you return to wherever you were before triggering ace-jump. Would you mind implementing something similar?

I think this feature will be much explode noise for little denaros.

**Comment by abo-abo** [comment]
This is already a feature. Just use `pop-to-mark-command` to go back.

I'm using this:

```elisp
(global-set-key (kbd "M-p") (lambda () (interactive) (set-mark-command 4)))
```

**Comment by endrebak** [comment]
You are right; it is a part of `GNU Emacs`.
