### ISSUE TITLE
Different colors for avy-background-face?

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/avy#70]
Hi there! It's me again. 

Maybe there is a bug. I use the following styling settings for `avy-goto-line` function. 

```
`(avy-background-face ((t (:foreground ,junza-yellow-1 :background  ,junza-red-2))))
 '(avy-background-face ((t (:background "#750000" :foreground "#BD9800"))))
 '(avy-lead-face ((t (:background "#750000" :foreground "#BD9800" :weight bold))))
```

Furthermore, I have the following settings set for Avy:

`(setq avy-keys (list ?s ?f ?g ?h ?j ?k ?l ?e ?w ?o))`. 

That's it. When I call `avy-goto-line`, I got the weird purple color like from the default Avy:

![untitled](https://cloud.githubusercontent.com/assets/5211845/8341169/6c9cd70a-1ac3-11e5-9e53-3c8ff7ffe620.png)

 The red/yellow colors at the right are the right colors. So I don't have any idea where the purple colors come from. When I'm typing the first letter, then the latest character is being displayed, and it's in the right color. 

Any suggestion where the purple color might come from. It's clearly not from my settings.

**Comment by abo-abo** [comment]
Have a look at:

```elisp
(defconst avy-lead-faces '(avy-lead-face
                           avy-lead-face-0
                           avy-lead-face-2
                           avy-lead-face
                           avy-lead-face-0
                           avy-lead-face-2)
  "Face sequence for `avy--overlay-at-full'.")
```

These are used in order, depending on how many chars are needed.  If three are needed, the first one will be `avy-lead-face`, the second - avy-lead-face-0, the third - `avy-lead-face-2`.  So you can just customize all three of them.

**Comment by ReneFroger** [comment]
I get it now. Thanks. I customized the avy-lead-face accidentially, when calling `customize-face` for avy, see also https://github.com/abo-abo/avy/issues/60. Since it stucked in my generated init. Hence why there is only one `avy-lead-face` customized, and not all the three. 

Thanks for your help.
