### ISSUE TITLE
Display letters in uppercase but require only lowercase input

### ISSUE THREAD

**Issue by endrebak** [abo-abo/avy#71]
I have an idea which I think will both be very easy to implement and make `avy` much easier to use.

It is to allow the user to input lowercase letters, but having the letters on the screen displayed in uppercase.

Uppercase letters are 1) easier to distinguish, 2) less used in code, so easier to tell apart from the surrounding text.

**Comment by endrebak** [comment]
You could also make it easy to have a very different font for `avy` letters, but I do not know how it will look in practice (perhaps too jarring with two fonts in one buffer?).

**Comment by abo-abo** [comment]
You can customize it like this:

```elisp
(setq avy-keys
      '(?A ?S ?D ?F ?G ?H ?J ?K ?L))
(setq avy-translate-char-function #'upcase)
```

**Comment by endrebak** [comment]
Wonderful, thanks.

**Comment by ardpp** [comment]
Wanted just mention one thing. I have tried this setting and it seems to interfere with ace-windows somehow. Using that I can do the first splitting using `ace-window` followed by `v` or `b`. Further attempts to split windows or jump between windows fail however.

**Comment by abo-abo** [comment]
@ardpp, thanks, I've fixed ace-window.
