### ISSUE TITLE
Avy letters displayed with different font?

### ISSUE THREAD

**Issue by endrebak** [abo-abo/avy#72]
To make `avy` letters more distinguishable from the surrounding text you could try allowing the user to select a different font for `avy` text. 

I do not know how this will look in practice (perhaps too jarring with two fonts in one buffer?).

**Comment by endrebak** [comment]
This seems to be doable in `M-x <RET> customize-group <RET> avy <RET>`.

**Comment by abo-abo** [comment]
Exactly.

**Comment by endrebak** [comment]
Yes, very possible. Need to play around with the height to ensure the lines aren't shifted slightly. And can choose to use strikethrough instead of different colors for matched text.
