### ISSUE TITLE
Respect current input method when reading target char

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/avy#76]
`avy` can be easily used with non-Latin languages. You're currently reading target char like this: `(read-char "char: ")`, just add optional argument `inherit-input-method` and people will be able to use `avy` to navigate any sort of text: `(read-char "char: " t)`. I don't know any reason why current input should not be taken into account. Users who are not interested in non-Latin languages usually don't enable input methods, so they won't notice any changes, however if you have activated some input method, changes are that you're editing text that consists of characters the input method provides. So, I think this change would be good from all points of view. What do you think?

**Comment by abo-abo** [comment]
Good idea, thanks.

**Comment by mrkkrp** [comment]
This does not seem to work anymore.

**Comment by abo-abo** [comment]
Works fine for me, all the `(read-char "char: " t)` code is still there.

**Comment by mrkkrp** [comment]
Oh, sorry, it works indeed. I tried with a minor mode enabled so it ifluenced this thing. Avy works fine.
