### ISSUE TITLE
Support avy-goto-subword-1?

### ISSUE THREAD

**Issue by aethanyc** [abo-abo/avy#8]
Will we have avy-goto-subword-1 which reads one char first, and jump to subwords? This should be useful for jumping CamelCaseWord identifiers.

**Comment by abo-abo** [comment]
Added, thanks.

**Comment by aethanyc** [comment]
@abo-abo: Thank you very much! I've always wanted this feature in ace-jump-mode. Now I can use your awesome `avy`!
