### ISSUE TITLE
2-letter paths for 10 candidates using avy-goto-word-1

### ISSUE THREAD

**Issue by env0der** [abo-abo/avy#80]
I have this text visible on a screen (it's a portion of buffer):

```elisp
  (use-package ctags-update
    :config
    (progn
      (setq ctags-update-delay-seconds 0)
      (setq tags-revert-without-query t)
      (global-auto-revert-mode t)
      (setq auto-revert-verbose nil)
      (add-hook 'after-save-hook 'ctags-update)
      (evil-leader/set-key "pR" 'ctags-update))))

(defun env0der/init-nlinum ()
  (use-package nlinum
    :config
    (progn
      (global-nlinum-mode t)
      (setq nlinum-format "%d "))))

(defun env0der/init-ag ()
  (use-package ag))

(defun env0der/init-browse-at-remote ()
  (use-package browse-at-remote))

(defun env0der/init-osx-clipboard ()
  (use-package osx-clipboard
    :config
    (progn
      (osx-clipboard-mode +1)
      (diminish 'osx-clipboard-mode))))

(defun env0der/init-avy ()
  (use-package avy
    :config
    (progn
      (setq avy-background t)
      (define-key evil-normal-state-map (kbd "SPC") 'avy-goto-word-or-subword-1))))
```

Using ```avy-goto-word-1``` to find words that begin with ```u``` shows 2-letter paths for last 2 candidates. I think it would be more convenient to have 1-letter paths as long as number of candidates is less than number of English letters.

**Comment by abo-abo** [comment]
> Using avy-goto-word-1 to find words that begin with u shows 2-letter paths for last 2 candidates. I think it would be more convenient to have 1-letter paths as long as number of candidates is less than number of English letters.

Avy always shows the shortest path possible for the current setting of `avy-keys`.

The default setting is:

    (setq avy-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))

The reason for this setting is that all keys are on the home row, so it's sometimes faster to press 2 keys on the home row rather than 1 off home row.

You can customize it to include all letters like this:

    (setq avy-keys (number-sequence ?a ?z))

If you want the capital letters as well:

    (setq avy-keys (concat (number-sequence ?a ?z)
                           (number-sequence ?A ?Z)))

**Comment by env0der** [comment]
Nice, did not know about this setting.
Дякую! :)
