### ISSUE TITLE
ace-jump-mode-pop-mark

### ISSUE THREAD

**Issue by c02y** [abo-abo/avy#81]
Is there any function in avy that does what `ace-jump-mode-pop-mark` does that will jump back the position before jumping? I cannot find it in the source code, if it does, I can use avy to replace ace-jump-mode completely.

**Comment by abo-abo** [comment]
Just added this. I've had this one as an anonymous lambda for years, way before `avy`.

**Comment by c02y** [comment]
[This](https://github.com/abo-abo/avy/commit/492ac494e9cce18b22ddacfdf09da86be19a0f42) seems relatively too simple, checkout [ace-jump-mode-pop-mark](https://github.com/winterTTr/ace-jump-mode/blob/master/ace-jump-mode.el#L700-L750), it can jump across buffers.
