### ISSUE TITLE
Selecting, moving, and then invoking an avy command does not preserve the initial point of selection

### ISSUE THREAD

**Issue by chrisf1337** [abo-abo/avy#84]
When selecting text, sometimes I will start moving before invoking an avy command. It seems like a new selection is created and I end up selecting the text from the point at which I invoked the avy command instead of starting from the initial selection point. I tried to illustrate below what I'm describing.

```
^ Cursor position
- Selected text

Start
*****
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt
      ^

After starting selection and moving
***********************************
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt
      ----------------------------------^

After invoking an avy command
*****************************
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt
                                        -----------------^

Expected behavior
*****************
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt
      ---------------------------------------------------^
```

I'm wondering if this is intended behavior. Thanks!

**Comment by abo-abo** [comment]
Thanks. It's strange that no one else has brought this up.

**Comment by tam17aki** [comment]
This commits really effective for ace-isearch with avy. Thank you.
https://github.com/tam17aki/ace-isearch

**Comment by abo-abo** [comment]
You're welcome!
