### ISSUE TITLE
Feature request: Take other actions when typing a non-character key in `avy-goto-word-1`

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/avy#85]
When I call `avy-goto-word-1`, it asks me for a character to jump to. If I type a non-character key like `M-d` or `M-l`, it just errors out.

It would be nice if I could use non-character keys to act as modifiers of sort on the action that's about to be done. For instance, let's say `avy-goto-word-1` is bound to `M-s` for me:

1. If I hit `M-s o` (or any other character), I get the usual behavior of jumping to words that start with that character.
3. If I hit `M-s M-d`, I get the usual `avy-goto-word-1` behavior of prompting me for a character to jump to, but instead of jumping to that position it would kill the text between point and the position I specify.
4. If I hit `M-s M-w`, I get the same as `3`, but with copying instead of killing.
2. If I hit `M-s M-l`, that puts me in `avy-goto-line` instead.

Get where I'm going with this? :)

I think it would be a nice addition, and you wouldn't lose anything. The usual behavior of just jumping to a word still works exactly the same way as before (with no extra keys). You'd just be making productive use of all those `M-` keys that are currently useless.

**Comment by abo-abo** [comment]
There is already a feature in place for this:

- <kbd>M-s a</kbd> goes to words that start with `a`.
- <kbd>M-s a x</kbd> kills words that start with `a`.
- <kbd>M-s a m</kbd> marks words that start with `a`.
- <kbd>M-s a n</kbd> copies words that start with `a` without moving there.

If you want to kill with <kbd>M-d</kbd> instead of <kbd>x</kbd>, use:

```elisp
(setq avy-dispatch-alist
      `((?x . avy-action-kill)
        (?m . avy-action-mark)
        (?n . avy-action-copy)
        (,(aref (kbd "M-d") 0) . avy-action-kill)))
```

Here, the functions only take one argument - the selected point. You could write your own easily if kill/mark/copy aren't enough.

**Comment by Malabarba** [comment]
> M-s a x kills words that start with a.

What is M-s bound to in this case? avy-goto-word doesn't do that for me.

**Comment by abo-abo** [comment]
(global-set-key (kbd "M-s") 'avy-goto-word-1)

First you call the command. This one requires the first char, so that has to be entered too.  At this stage, you should get the overlays. Pressing <kbd>x</kbd> here should switch the operation from `goto` to `kill`.  But only if `x` isn't on `avy-keys`.

**Comment by Malabarba** [comment]
> But only if x isn't on avy-keys.

I see now, that's why I was confused. :) 
Thanks for the explanation. 

The other method would have been more convenient with the `goto-line` example. But I don't use goto-line that often, so this should be fine for me.

Thanks again

**Comment by Malabarba** [comment]
> > But only if x isn't on avy-keys.

> I see now, that's why I was confused. :) 

Actually, no. The reason I was confused is that I'm on melpa stable. :)

**Comment by Malabarba** [comment]
Oh no wait. I was still on the old `avy-jump`. :P Well that's embarassing.

**Comment by abo-abo** [comment]
> I was still on the old avy-jump. :P Well that's embarassing.

Happens to everyone at some point:)

**Comment by abo-abo** [comment]
Also, this feature is rather new, and just a response to a user who hasn't given feedback on it yet.  So it would be nice to also get some feedback and comments from you. Maybe implementing it another way is better, for instance applying the modifier before the first letter is read and not after. Or maybe you want more/different actions.

**Comment by Malabarba** [comment]
>  Maybe implementing it another way is better, for instance applying
>  the modifier before the first letter is read and not after. 

Personally, I think applying the modifier before would be easier and faster for me. The current version requires that I press the modifier between giving a character and specifying which character I want (which would normally two very fast keystrokes).

For instance, here's how my brain goes when using the feature:

1. “I want to copy something” Press `M-s`
2. “The thing is over there” Press the leading char
3. “I want to copy something” Press `w` (the modifier key)
4. “The thing is over there” Press the key displayed on avy's overlay

If the modifier were pressed first, I think it would go more or less like this:

1. “I want to copy something” Press `M-s M-w`
2. “The thing is over there” Press the leading char and then the key displayed on avy's overlay

See what I mean?

Additionally, if there's only one word starting with the given character then avy will just jump right to it, and the user won't have a chance to type a modifier,

> or maybe you want more/different actions.

I did, but I'm not so sure anymore. Originally I wanted actions like killing text *between* the origin and destination point (instead of killing the word at the destination). But I later realised that that's equivalent to just hitting `C-w` after the jump, which takes the same number of keystrokes.

**Comment by a13** [comment]
>Additionally, if there's only one word starting with the given character then avy will just jump right to it, and the user won't have a chance to type a modifier,

exactly the problem I have now
