### ISSUE TITLE
Request: Have avy-goto-line honor numeric prefix args

### ISSUE THREAD

**Issue by dangitall** [abo-abo/avy#86]
I can type `M-8 M-g M-g` to go to line 8 right now (with `goto-line`), but `avy-goto-line` only seems to accept the numeric argument as a regular argument. If you specify it as a prefix arg it acts as if there was no arg at all (as far as I can tell). It would be nice if mimicked the `goto-line` behavior in this regard so it could be a better drop-in.

**Comment by abo-abo** [comment]
Thanks.

**Comment by dangitall** [comment]
Thank you! There is a slight bug in that if I specify the line number via the prefix arg, it actually takes me to one line after the one I requested.
