### ISSUE TITLE
avy-pop-mark doesn't jump back across windows or frames

### ISSUE THREAD

**Issue by bmag** [abo-abo/avy#88]
`avy` is great, but there is one issue that bothers me. It is related to #69 and #81.
After using `avy-goto-word-or-subword-1` to jump to another buffer (in another window or frame), `avy-pop-mark` doesn't jump back to the previous buffer. I also tried `pop-global-mark`, but that didn't jump back either. Any chance to address this issue?

**Comment by abo-abo** [comment]
Should work better now. Please check.

**Comment by bmag** [comment]
Thanks for the quick response, it mostly works.
Jumping back in the same window or across windows does work. However, when jumping back across frames, the previous frame doesn't gain focus.
Also, very weird - jumping back in the same window in an `org` buffer doesn't work. I get "Wrong type argument: stringp, nil"

**Comment by abo-abo** [comment]
> jumping back across frames, the previous frame doesn't gain focus.

Fixed.

> Also, very weird - jumping back in the same window in an org buffer doesn't work. I get "Wrong type argument: stringp, nil"

This is likely unrelated to avy. Try to reproduce with a clean config.

**Comment by bmag** [comment]
Right, the error was on my part. I bound `avy-pop-mark` globally for easier testing, but that key was shadowed by an org binding.
Thanks alot :+1:
