### ISSUE TITLE
Ava-goto-line jumping to "virtual" lines for visual line mode

### ISSUE THREAD

**Issue by sooheon** [abo-abo/avy#91]
If avy-goto-line is thought of a way to jump to a line you see in the buffer, not necessarily a logical line which can exist anywhere in the file, it would make sense to let it jump to virtual lines created by visual-line-mode. 

Is it possible?

<img width="686" alt="screen shot 2015-08-17 at 11 41 04 pm" src="https://cloud.githubusercontent.com/assets/302945/9307429/70385042-4539-11e5-9d9c-a5e4f648d847.png">

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by sooheon** [comment]
Nice, it works in most cases perfectly, but I've found a few bugs.

1. If the last visible line (paragraph) wraps and ends outside of the visible buffer, avy-goto-line returns `line-move-visual: End of buffer`. Reproducible by copy pasting lorem ipsum from [here](http://www.lipsum.com/feed/html), turning on visual-line-mode, and scrolling buffer to cut off the last visible line.
2. Sometimes, when you've been moving around between lines with `C-n` and `C-p`, it will get into a weird state and display the avy-overlays in the middle of lines. I have yet to find reproducible steps, but with visual-line mode and navigating around some wrapped text, it happens frequently.
<img width="686" alt="screen shot 2015-08-22 at 1 14 32 am" src="https://cloud.githubusercontent.com/assets/302945/9413177/47c0f184-486b-11e5-940b-33b14f465d06.png">
3. This only occurs with org-indent mode, so maybe too much of an edge case to support, but the way that avy prepends indicators to line-wrapped and auto-indented lines can de-indent the second visual line (as in "e" and "o") and pull forward the subsequent overlays ("r", "v", "m", "n").
<img width="686" alt="screen shot 2015-08-22 at 12 55 47 am" src="https://cloud.githubusercontent.com/assets/302945/9412744/8af59ae8-4868-11e5-9370-7c3d3a099481.png">

And while the screenshots are with evil-mode, I have reproduced them with emacs -Q and loading just avy and org as well.

**Comment by sooheon** [comment]
@abo-abo do you mind taking one more look at problem cases 2 and 3? The way avy creates overlays at visual lines (but in the middle of logical lines) seems to create problems. 3 seems to be the more egregious case as it pulls the overlay up to the previous line.

**Comment by abo-abo** [comment]
Please add reproducible recipes for cases 2 and 3 in separate new issues.
