### ISSUE TITLE
Bloody Leuven

### ISSUE THREAD

**Issue by louy2** [abo-abo/avy#92]
Drama:
Avy makes [Leuven](https://github.com/fniessen/emacs-leuven-theme/issues) all bloody!

Technical:
When avy is showing candidates under theme leuven, the background, instead of staying unchanged, turns red.

**Comment by abo-abo** [comment]
Looks like that's the intent of the theme, [see](https://github.com/fniessen/emacs-leuven-theme/blob/master/leuven-theme.el#L295). Nothing I can do here.

**Comment by louy2** [comment]
Oh wow. Okay. Thank you for digging that out.

**Comment by abo-abo** [comment]
You can set `avy-background` to nil if you don't want a background at all, it's actually nil by default.

**Comment by louy2** [comment]
Yep, done that. Thx anyway.
