### ISSUE TITLE
avy-word-punc-regexp in avy-goto-subword-1

### ISSUE THREAD

**Issue by env0der** [abo-abo/avy#93]
Hi @abo-abo ,

Would it be possible for ```avy-goto-subword-1``` to take ```avy-word-punc-regexp``` into account?
I'm using ```avy-goto-word-or-subword-1``` and I would like to be able to jump to words beginning from ```@``` for example which is very common in Ruby.

**Comment by abo-abo** [comment]
I don't see it here. I use `avy-goto-word-or-subword-1` and type `@` and it just works. Does that not work for you?

**Comment by abo-abo** [comment]
Oh, i see it - forgot to enable `subword-mode`.

**Comment by abo-abo** [comment]
You have to customize your Emacs like this:

```elisp
(setq subword-backward-regexp
      "\\(\\(\\W\\|[[:lower:][:digit:]]\\)\\([@[:upper:]]+\\W*\\)\\|\\W\\w+\\)")
```

I can't change that variable in avy, since packages shouldn't do that. Note that I only added a single `@` when compared to the default value of `subword-backward-regexp`.  You can add more chars if you want.

**Comment by abo-abo** [comment]
I decided on binding `subword-backward-regexp` temporarily, so it should all be automatic now.

**Comment by env0der** [comment]
Thank you! :+1:
