### ISSUE TITLE
Constant margin for avy-goto-line

### ISSUE THREAD

**Issue by hatschipuh** [abo-abo/avy#95]
Hi, 

I had the idea that it would be nice to have the avy-goto-line characters constantly in the left window margin. Is this achievable or would it be complicated? Would you be interested to add this feature?

**Comment by abo-abo** [comment]
I don't see how this can be very useful. However, if you want to implement it as an off-by-default option, and you have the Emacs copyright assignment in case the change is over 15 lines, I'll accept a PR.

**Comment by hatschipuh** [comment]
It's just a personal preference. I don't like things "popping up" and the use case for me would be to use it like relative-line-number mode which let's you jump to other lines quickly by typing the relative line number. The problem is that number are harder to reach so I want something like this but with characters. I don't know how to do this, yet but if I learned then I will try  ;)

I don't really know what you mean by Emacs coyright assignment, could you explain?

**Comment by abo-abo** [comment]
> I don't know how to do this yet but if I learned then I will try ;)

OK, it's just a matter of making e.g. `avy--overlay-at-full` look like `relative-line-numbers--make-overlay`.

> I don't really know what you mean by Emacs coyright assignment, could you explain?

Anyone who contributes to core Emacs, Org-mode, or packages in [GNU ELPA](https://elpa.gnu.org/packages/) has to sign the agreement that their changes to Emacs have the FSF as the copyright holder, while you are only the author, [see also](https://github.com/abo-abo/avy#copyright-assignment).

**Comment by hatschipuh** [comment]
Ok, thanks for your time and your work in general. I really appreciate it.
